package com.cnlaunch.golo;

import java.io.Serializable;
import java.util.List;

public class InterfaceConfig implements Serializable {
    public static String ACCOUNT_ADD_AMOUNT = null;
    public static String ACCOUNT_GET_DATA = null;
    public static String ACCOUNT_MULIT_ADD = null;
    public static String AREA_GET_CITY = null;
    public static String AREA_GET_COUNTRY = null;
    public static String AREA_GET_COUNTRY_LIST = null;
    public static String AREA_GET_PROVINCE = null;
    public static String BLACKLIST_ADD = null;
    public static String BLACKLIST_DELETE = null;
    public static String BLACKLIST_IS_BLACKLIST = null;
    public static String BLACKLIST_LIST = null;
    public static String BLACKLIST_LIST_CAR_LOGO = null;
    public static String COLLECT_ADD = null;
    public static String COLLECT_DELETE = null;
    public static String COLLECT_FILE = null;
    public static String COLLECT_GET = null;
    public static String CONFIGURE_CONFIG_CARS = null;
    public static String CONFIGURE_GET_CARS = null;
    public static String CONFIG_AREA = null;
    public static String CONFIG_NO = null;
    public static String CONFIG_URLS = null;
    public static String CREATE_PICK_ME_UP_MISSION = null;
    public static String DATASTREAM_GETDFDATALISTT = null;
    public static String DATASTREAM_GETFAULTCODES = null;
    public static String DATASTREAM_GETOBDDATALIST = null;
    public static String DATASTREAM_GETSYSDATASTREAM = null;
    public static String DB_DOWNLOAD = null;
    public static String DELETE_EFENCE = null;
    public static String DELETE_MISSION_INFO = null;
    public static String DIAGSOFT_DOWNLOAD = null;
    public static String EDITE_EFENCE = null;
    public static String FILE_UPLOAD = null;
    public static String FRIEND_ADD = null;
    public static String FRIEND_ADDF = null;
    public static String FRIEND_ADDMOBILEFRI = null;
    public static String FRIEND_DELETE = null;
    public static String FRIEND_DETAIL = null;
    public static String FRIEND_DETAIL_CAR_LOGO = null;
    public static String FRIEND_ENSURE_ADD = null;
    public static String FRIEND_LIST = null;
    public static String FRIEND_LIST_CAR_LOGO = null;
    public static String FRIEND_MOBILEBOOK = null;
    public static String FRIEND_REC_CARFRI = null;
    public static String FRIEND_REC_TECHNICIAN = null;
    public static String FRIEND_RENAME = null;
    public static String FRIEND_SLIST = null;
    public static String FRIEND_VALID_ADDF = null;
    public static String FRIEND_WAGGLE = null;
    public static String FRIEND_WAGGLE_CAR_LOGO = null;
    public static String GET_DEVICE_STATUS = null;
    public static String GET_EFNCE_INFO = null;
    public static String GET_EXPERT = null;
    public static String GET_MILEAGE_RECORD = null;
    public static String GET_MONITOR_NEW_RECORD = null;
    public static String GET_PICK_ME_UP_MISSION_RECORD = null;
    public static String GET_PUBLIC_MAX_VERSION = null;
    public static String GET_RANKING = null;
    public static String GET_ROUTE_BLACK_PLAY = null;
    public static String GET_SHARE_MILEAGE_RECORD = null;
    public static String GET_SHARE_TRAFFIC = null;
    public static String GET_SHARE_USERINFO = null;
    public static String GPS_INFO_GET_DATA = null;
    public static String GPS_INFO_GET_HISITORY_POSITION_RECORD = null;
    public static String GPS_INFO_GET_MILEAGE = null;
    public static String GROUP_CREATE = null;
    public static String GROUP_GLIST = null;
    public static String GROUP_INVITE = null;
    public static String GROUP_KICKED = null;
    public static String GROUP_LIST = null;
    public static String GROUP_MEMBER = null;
    public static String GROUP_MEMBER_DETAIL = null;
    public static String GROUP_QUIT = null;
    public static String GROUP_RELIEVE = null;
    public static String GROUP_SAVE = null;
    public static String GROUP_UPDATE_NAME = null;
    public static String HELP_FEEDBACK = null;
    public static String LBS_CLEAR_LOCATION = null;
    public static String LBS_GET_NEARBY = null;
    public static String LBS_GET_NEARBY_PUBLIC = null;
    public static String LBS_GET_NEARBY_REPAIRSHOP = null;
    public static String LBS_MILEAGE_SERVICE_GET_NEARBY = null;
    public static String LBS_UPDATE_LOCATION = null;
    public static String LOGIN = null;
    public static String MAP_DELETE_ROUTE = null;
    public static String MAP_GET_CAR_LOCATION = null;
    public static String MAP_MAP_POINT_RECTIFY = null;
    public static String MAP_MY_CAR_LOCATION = null;
    public static String MILEAGE_DATA = null;
    public static String MINE_CAR_GET_MINE_CAR_LIST = null;
    public static String MINE_CAR_QUERY_AUTO_LOGOS = null;
    public static String MINE_CAR_QUERY_CAR_PLATE_PREFIX = null;
    public static String MINE_CAR_QUERY_CAR_SERIES_CONFIG = null;
    public static String MINE_CAR_QUERY_CAR_TYPE = null;
    public static String MINE_CAR_QUERY_MINE_CAR_INFO = null;
    public static String MINE_CAR_QUERY_X431_CAR_SERIES = null;
    public static String MINE_CAR_QUERY_X431_CAR_SERIES_WORLD = null;
    public static String MINE_CAR_REMOVE_MINE_CAR = null;
    public static String MINE_CAR_SAVE_MINE_CAR_INFO = null;
    public static String MINE_CAR_UPDATE_MINE_CAR = null;
    public static String MINE_CAR_UPLOAD_MODIFY_MINE_CAR_IMAGE = null;
    public static String MODIFY_MISSION_INFO = null;
    public static String ONE_KEY_DIAG_BEGIN_ONE_KEY_DIAG_CALC = null;
    public static String ONE_KEY_DIAG_GET_CAR_BRAND_LIST_FOR_DBSCAR_PRO = null;
    public static String ONE_KEY_DIAG_GET_CONFIGED_ALL_INFO = null;
    public static String ONE_KEY_DIAG_GET_CONFIGED_INI_FILE_INFO = null;
    public static String ONE_KEY_DIAG_GET_DIAG_SOFT_MAX_VERSION_BY_SERIAL_NO = null;
    public static String ONE_KEY_DIAG_GET_OBD_VERSION_DETAIL_ID = null;
    public static String ONE_KEY_DIAG_GET_ODB_INI_FILE_INFO = null;
    public static String ONE_KEY_DIAG_GET_SOFT_INFO_FOR_DBSCAR_PRO = null;
    public static String ONE_KEY_DIAG_ONE_KEY_DIAG_CALC = null;
    public static String PECCANCY_FIND = null;
    public static String PECCANCY_QUERY = null;
    public static String PECCANCY_TEMP_FIND = null;
    public static String POST_ATTITUDE_ADD = null;
    public static String POST_ATTITUDE_DELETE = null;
    public static String POST_COMMENT_ADD = null;
    public static String POST_COMMENT_DELETE = null;
    public static String POST_DELETE = null;
    public static String POST_FILE = null;
    public static String POST_FRIENDS = null;
    public static String POST_GET = null;
    public static String POST_GET_BLACKLIST = null;
    public static String POST_GET_CONFIG = null;
    public static String POST_GET_DETAIL = null;
    public static String POST_GET_FRIENDIMG = null;
    public static String POST_GET_NOSEE = null;
    public static String POST_GET_PUBLIC_EVALUATION = null;
    public static String POST_MESSAGE = null;
    public static String POST_PUBLIC = null;
    public static String POST_PUBLISH = null;
    public static String POST_SELF = null;
    public static String POST_SET_BLACKLIST = null;
    public static String POST_SET_CONFIG = null;
    public static String POST_SET_NOSEE = null;
    public static String POST_SHARE_HOME_PAGE_GET = null;
    public static String POST_SHARE_HOME_PAGE_SET = null;
    public static String POST_SHARE_HOT_CITY_GET = null;
    public static String POST_TECHNICIAN = null;
    public static String POST_TRANSPOND = null;
    public static String PRODUCT_CHECK_PRODUCT_UPDATE = null;
    public static String PRODUCT_PUB_APPLY_BIND_PUB = null;
    public static String PRODUCT_PUB_UNBIND_PUB = null;
    public static String PRODUCT_REGIST_PRODUCT = null;
    public static String PUBACCOUNT_LIST_PUB = null;
    public static String PUBACCOUNT_LIST_TECH_BYP = null;
    public static String PUBACCOUNT_PID_BYT = null;
    public static String PUBACCOUNT_PUB_DETAIL = null;
    public static String PUBACCOUNT_PUB_DETAIL_SORT = null;
    public static String PUBACCOUNT_REC_PUBLIC = null;
    public static String PUBACCOUNT_SEARCH_LIKE = null;
    public static String PUBACCOUNT_USER_ATTENTION_PUB = null;
    public static String PUBACCOUNT_USER_BIND_PUB = null;
    public static String PUBACCOUNT_USER_REMOVE_PUB = null;
    public static String PUBACCOUNT_USER_UNBIND_PUB = null;
    public static String PUBLIC_EXPERT_ADD_GRADE = null;
    public static String PUBLIC_EXPERT_ADD_RECORD = null;
    public static String PUBLIC_EXPERT_GET_TECH_DETAIL = null;
    public static String PUBLIC_USERS = null;
    public static String QUERY_SERIAL_NO_MAX_VERSION = null;
    public static String REGISTER = null;
    public static String REG_USER = null;
    public static String REPORT_DELETE = null;
    public static String REPORT_QUERY = null;
    public static String REPORT_QUERY_DIAGNOSTIC = null;
    public static String REPORT_UPLOAD = null;
    public static String REPORT_UPLOAD_DIAGNOSTIC = null;
    public static String SAVE_EFENCE = null;
    public static String SET_DEFAULT_CEHICLE = null;
    public static String SET_TECH_CUSTOMER_REVIEW = null;
    public static String SHARE_ALARM_DEL = null;
    public static String SHARE_ALARM_GET = null;
    public static String SHARE_ALARM_SET = null;
    public static String SIM_CARD_CREATE_CHARGE_ORDER = null;
    public static String SIM_CARD_CREATE_INVOICE = null;
    public static String SIM_CARD_DO_ALIPAY_VERIFY = null;
    public static String SIM_CARD_GET_CHARGE_SERIES = null;
    public static String SIM_CARD_GET_FLOW_BY_SERIAL = null;
    public static String USERINFO_SET_PASSWORD = null;
    public static String USER_GETPRODUCTS = null;
    public static String USER_GET_BASE_INFO = null;
    public static String USER_GET_BASE_INFO_CAR_LOGO = null;
    public static String USER_GET_COMMON = null;
    public static String USER_GET_CONTACT = null;
    public static String USER_GET_FACE = null;
    public static String USER_GET_HOBBY = null;
    public static String USER_GET_MAPCONF = null;
    public static String USER_GET_PRICONF = null;
    public static String USER_GET_RAND_HOBBY = null;
    public static String USER_GET_WEATHER = null;
    public static String USER_SEARCH = null;
    public static String USER_SEARCH_BY_CAR = null;
    public static String USER_SEARCH_CAR_LOGO = null;
    public static String USER_SEARCH_DETAIL = null;
    public static String USER_SET_AREA = null;
    public static String USER_SET_BASE = null;
    public static String USER_SET_CONF = null;
    public static String USER_SET_EXT = null;
    public static String USER_SET_FACE = null;
    public static String USER_UNBIND_EMAIL = null;
    public static String USER_UNBIND_TEL = null;
    public static String VEHICLE_ADD = null;
    public static String VEHICLE_DEL = null;
    public static String VEHICLE_EXAMINATION = null;
    public static String VEHICLE_FIND = null;
    public static String VEHICLE_SET = null;
    public static String VERIFY_REQUEST_SEND_CODE = null;
    public static String VERIFY_REQ_SEND_CODE = null;
    public static String VERIFY_RESET_PASS = null;
    public static String VERIFY_UPDATE_SERIAL_NO_VERSION = null;
    public static String VERIFY_VERIFY_CODE = null;
    public static String VERSION_LAST = null;
    public static String VERSION_LATEST = null;
    public static String WARNING_GET_HISTORY = null;
    public static String WARNING_GET_ITEMS = null;
    public static String WARNING_SETWARNING = null;
    public static String WARNING_SET_PARAM = null;
    private static final long serialVersionUID = -4943596269595205500L;
    private String area;
    private String code;
    private String msg;
    private List<InterfaceUrl> urlList;
    private String version;

    static {
        CONFIG_URLS = "config.urls";
        CONFIG_AREA = "config_area";
        CONFIG_NO = "config_no";
        USER_GET_BASE_INFO = "user.get_base_info";
        USER_GET_WEATHER = "user.get_weather";
        USER_GET_BASE_INFO_CAR_LOGO = "user.get_base_info_car_logo";
        USER_SET_BASE = "user.set_base";
        USER_SET_AREA = "user.set_area";
        USER_UNBIND_TEL = "user.unbind_tel";
        USER_UNBIND_EMAIL = "user.unbind_email";
        USER_GET_CONTACT = "user.get_contact";
        USER_SET_EXT = "user.set_ext";
        USER_GET_PRICONF = "user.get_priconf";
        USER_GET_MAPCONF = "user.get_map_conf";
        USER_SET_CONF = "user.set_conf";
        USER_GET_COMMON = "user.get_common";
        USER_GET_RAND_HOBBY = "user.get_rand_hobby";
        USER_GET_HOBBY = "user.get_hobby";
        VERIFY_REQ_SEND_CODE = "verify.req_send_code";
        VERIFY_REQUEST_SEND_CODE = "verify.request";
        VERIFY_VERIFY_CODE = "verify.verify_code";
        VERIFY_RESET_PASS = "verify.reset_pass";
        USERINFO_SET_PASSWORD = "userinfo.set_password";
        AREA_GET_COUNTRY_LIST = "area.get_country_list";
        AREA_GET_COUNTRY = "area.get_country";
        AREA_GET_PROVINCE = "area.get_province";
        AREA_GET_CITY = "area.get_city";
        LBS_GET_NEARBY = "lbs.get_nearby";
        LBS_CLEAR_LOCATION = "lbs.clear_location";
        LBS_UPDATE_LOCATION = "lbs.update_location";
        LBS_GET_NEARBY_REPAIRSHOP = "lbs.get_nearby_repairshop";
        HELP_FEEDBACK = "feedback.post";
        LOGIN = "login";
        REGISTER = "register";
        USER_SEARCH = "user.search";
        USER_SEARCH_CAR_LOGO = "user.search_car_logo";
        USER_SEARCH_DETAIL = "user.search1";
        USER_GET_FACE = "user.get_face";
        USER_SET_FACE = "user.set_face";
        FRIEND_ADD = "friend.add";
        FRIEND_ADDF = "friend.addf";
        FRIEND_ENSURE_ADD = "friend.ensure_add";
        FRIEND_VALID_ADDF = "friend.valid_addf";
        VERSION_LAST = "version.last";
        VERSION_LATEST = "version.latest";
        PUBLIC_USERS = "public.users";
        FILE_UPLOAD = "file.upload";
        GROUP_QUIT = "group.quit";
        GROUP_LIST = "group.list";
        GROUP_GLIST = "group.glist";
        GROUP_CREATE = "group.create";
        GROUP_INVITE = "group.invite";
        GROUP_MEMBER = "group.member";
        GROUP_MEMBER_DETAIL = "group.member_detail";
        GROUP_RELIEVE = "group.relieve";
        GROUP_KICKED = "group.kicked";
        GROUP_UPDATE_NAME = "group.update";
        GROUP_SAVE = "group.save";
        BLACKLIST_ADD = "blacklist.add";
        BLACKLIST_LIST = "blacklist.list";
        BLACKLIST_LIST_CAR_LOGO = "blacklist.list_car_logo";
        BLACKLIST_DELETE = "blacklist.delete";
        BLACKLIST_IS_BLACKLIST = "blacklist.is_blacklist";
        FRIEND_LIST = "friend.list";
        FRIEND_LIST_CAR_LOGO = "friend.list_car_logo";
        FRIEND_SLIST = "friend.slist";
        FRIEND_DETAIL = "friend.detail";
        FRIEND_DETAIL_CAR_LOGO = "friend.detail_car_logo";
        FRIEND_WAGGLE = "friend.waggle";
        FRIEND_WAGGLE_CAR_LOGO = "friend.waggle_car_logo";
        FRIEND_DELETE = "friend.delete";
        FRIEND_RENAME = "friend.rename";
        FRIEND_MOBILEBOOK = "friend.mobilebook";
        FRIEND_ADDMOBILEFRI = "friend.addmobilefri";
        FRIEND_REC_TECHNICIAN = "friend.rec_technician";
        FRIEND_REC_CARFRI = "friend.rec_carfri";
        PUBACCOUNT_REC_PUBLIC = "pubaccount.rec_public";
        USER_SEARCH_BY_CAR = "user.search_by_car";
        PUBACCOUNT_USER_ATTENTION_PUB = "pubaccount.user_attention_pub";
        PUBACCOUNT_USER_REMOVE_PUB = "pubaccount.user_remove_pub";
        PUBACCOUNT_USER_BIND_PUB = "pubaccount.user_bind_pub";
        PUBACCOUNT_USER_UNBIND_PUB = "pubaccount.user_unbind_pub";
        PRODUCT_PUB_APPLY_BIND_PUB = "product_pub.apply_bind_pub";
        PRODUCT_PUB_UNBIND_PUB = "product_pub.unbind_pub";
        PUBACCOUNT_LIST_PUB = "pubaccount.list_pub";
        PUBACCOUNT_PUB_DETAIL = "pubaccount.pub_detail";
        PUBACCOUNT_PUB_DETAIL_SORT = "pubaccount.public_detail";
        PUBACCOUNT_SEARCH_LIKE = "pubaccount.search_like";
        PUBACCOUNT_PID_BYT = "pubaccount.pid_byt";
        PUBACCOUNT_LIST_TECH_BYP = "pubaccount.list_tech_byp";
        USER_GETPRODUCTS = "user.getproducts";
        WARNING_GET_ITEMS = "warning.get_items";
        WARNING_SETWARNING = "warning.setwarning";
        WARNING_SET_PARAM = "warning_set_param";
        DATASTREAM_GETFAULTCODES = "datastream.getfaultcodes";
        DATASTREAM_GETSYSDATASTREAM = "datastream.getsysdatastream";
        DATASTREAM_GETOBDDATALIST = "datastream.getobddatalist";
        DATASTREAM_GETDFDATALISTT = "datastream.getdfdatalist";
        VEHICLE_FIND = "vehicle.find";
        VEHICLE_ADD = "vehicle.add";
        VEHICLE_SET = "vehicle.set";
        VEHICLE_DEL = "vehicle.del";
        PECCANCY_FIND = "peccancy.find";
        ACCOUNT_GET_DATA = "account.get_data";
        ACCOUNT_ADD_AMOUNT = "account.add_amount";
        ACCOUNT_MULIT_ADD = "account.mulit_add";
        VEHICLE_EXAMINATION = "vehicle.examination";
        CONFIGURE_GET_CARS = "configure.get_cars";
        CONFIGURE_CONFIG_CARS = "configure.config_cars";
        PRODUCT_REGIST_PRODUCT = "product.regist_product";
        ONE_KEY_DIAG_GET_CAR_BRAND_LIST_FOR_DBSCAR_PRO = "one_key_diag.get_car_brand_list_for_dbscar_pro";
        ONE_KEY_DIAG_BEGIN_ONE_KEY_DIAG_CALC = "one_key_diag.begin_one_key_diag_calc";
        ONE_KEY_DIAG_ONE_KEY_DIAG_CALC = "one_key_diag.one_key_diag_calc";
        ONE_KEY_DIAG_GET_SOFT_INFO_FOR_DBSCAR_PRO = "one_key_diag.get_soft_info_for_dbscar_pro";
        ONE_KEY_DIAG_GET_CONFIGED_ALL_INFO = "one_key_diag.get_configed_all_info";
        ONE_KEY_DIAG_GET_CONFIGED_INI_FILE_INFO = "one_key_diag.get_configed_ini_file_info";
        ONE_KEY_DIAG_GET_DIAG_SOFT_MAX_VERSION_BY_SERIAL_NO = "one_key_diag.get_diag_soft_max_version_by_serial_no";
        MINE_CAR_QUERY_CAR_SERIES_CONFIG = "mine_car.query_car_series_config";
        MINE_CAR_UPLOAD_MODIFY_MINE_CAR_IMAGE = "mine_car_upload.modify_mine_car_image";
        DIAGSOFT_DOWNLOAD = "diagsoft.download";
        DB_DOWNLOAD = "db.download";
        GET_PUBLIC_MAX_VERSION = "public_soft.get_max_version";
        ONE_KEY_DIAG_GET_ODB_INI_FILE_INFO = "one_key_diag.get_obd_ini_file_info";
        ONE_KEY_DIAG_GET_OBD_VERSION_DETAIL_ID = "one_key_diag.get_obd_version_detail_id";
        QUERY_SERIAL_NO_MAX_VERSION = "getSeriaNoMaxVersion";
        VERIFY_UPDATE_SERIAL_NO_VERSION = "updateSerialNoVersion";
        PRODUCT_CHECK_PRODUCT_UPDATE = "product.check_product_update";
        POST_PUBLISH = "post.publish";
        POST_TRANSPOND = "post.transpond";
        POST_DELETE = "post.delete";
        POST_COMMENT_ADD = "post.comment_add";
        POST_COMMENT_DELETE = "post.comment_delete";
        POST_ATTITUDE_ADD = "post.attitude_add";
        POST_ATTITUDE_DELETE = "post.attitude_delete";
        POST_SHARE_HOME_PAGE_SET = "post.set_home";
        POST_SHARE_HOME_PAGE_GET = "post.get_home";
        POST_SHARE_HOT_CITY_GET = "post.hot_city";
        POST_SELF = "post.self";
        POST_FRIENDS = "post.friends";
        POST_GET = "post.get";
        POST_MESSAGE = "post.message";
        POST_FILE = "post.file";
        POST_PUBLIC = "post.public";
        POST_TECHNICIAN = "post.technician";
        POST_SET_CONFIG = "post.set_config";
        POST_GET_CONFIG = "post.get_config";
        POST_SET_BLACKLIST = "post.set_blacklist";
        POST_GET_BLACKLIST = "post.get_blacklist";
        POST_GET_FRIENDIMG = "post.pic";
        POST_GET_DETAIL = "post.detail";
        PUBLIC_EXPERT_GET_TECH_DETAIL = "public_expert.get_tech_detail";
        POST_GET_PUBLIC_EVALUATION = "public_expert.get_customer_review_for_tech";
        REG_USER = "reg_user";
        POST_SET_NOSEE = "post.set_nosee";
        POST_GET_NOSEE = "post.get_nosee";
        COLLECT_ADD = "collect.add";
        COLLECT_GET = "collect.get";
        COLLECT_DELETE = "collect.delete";
        COLLECT_FILE = "collect.file";
        MAP_MAP_POINT_RECTIFY = "map.map_point_rectify";
        MINE_CAR_SAVE_MINE_CAR_INFO = "mine_car.save_mine_car_info";
        MINE_CAR_GET_MINE_CAR_LIST = "mine_car.get_mine_car_list";
        MINE_CAR_QUERY_MINE_CAR_INFO = "mine_car.query_mine_car_info";
        MINE_CAR_UPDATE_MINE_CAR = "mine_car.update_mine_car";
        MINE_CAR_REMOVE_MINE_CAR = "mine_car.remove_mine_car";
        MINE_CAR_QUERY_X431_CAR_SERIES = "mine_car.query_x431_car_series";
        MINE_CAR_QUERY_X431_CAR_SERIES_WORLD = "mine_car.query_x431_car_series_world";
        GPS_INFO_GET_HISITORY_POSITION_RECORD = "gps_info.get_hisitory_position_record";
        GPS_INFO_GET_MILEAGE = "gps_info.get_mileage";
        LBS_MILEAGE_SERVICE_GET_NEARBY = "lbs_mileage_service.get_nearby";
        GPS_INFO_GET_DATA = "gps_info.get_data";
        REPORT_UPLOAD = "report.upload";
        REPORT_QUERY = "report.query";
        REPORT_DELETE = "report.del_medical_report";
        PECCANCY_TEMP_FIND = "peccancy.temp_find";
        PECCANCY_QUERY = "peccancy.query";
        REPORT_UPLOAD_DIAGNOSTIC = "report.upload_diagnostic";
        REPORT_QUERY_DIAGNOSTIC = "report.query_diagnostic";
        MINE_CAR_QUERY_CAR_TYPE = "mine_car.query_car_type";
        MINE_CAR_QUERY_CAR_PLATE_PREFIX = "mine_car.query_car_plate_prefix";
        WARNING_GET_HISTORY = "warning.get_history";
        SAVE_EFENCE = "bound_setting.add";
        DELETE_EFENCE = "bound_setting.delete";
        GET_EFNCE_INFO = "bound_setting.get_data";
        EDITE_EFENCE = "bound_setting.update";
        MILEAGE_DATA = "gps_info.get_data2";
        GET_EXPERT = "pubaccount.get_expert";
        MAP_GET_CAR_LOCATION = "gps_info.get_real_time_location";
        SET_TECH_CUSTOMER_REVIEW = "public_expert.set_tech_customer_review";
        PUBLIC_EXPERT_ADD_RECORD = "public_expert.add_record";
        PUBLIC_EXPERT_ADD_GRADE = "public_expert.add_grade";
        SHARE_ALARM_GET = "share_alarm.get";
        SHARE_ALARM_SET = "share_alarm.set";
        SHARE_ALARM_DEL = "share_alarm.del";
        MINE_CAR_QUERY_AUTO_LOGOS = "mine_car.query_auto_logos";
        LBS_GET_NEARBY_PUBLIC = "lbs.get_nearby_public";
        MAP_DELETE_ROUTE = "gps_info.del_trave";
        GET_SHARE_TRAFFIC = "realtime.get_cdt";
        GET_SHARE_USERINFO = "realtime.get_detail";
        MAP_MY_CAR_LOCATION = "gps_info.get_car_info";
        GET_DEVICE_STATUS = "gps_info.get_device_status";
        GET_MILEAGE_RECORD = "gps_info.get_trip_record";
        GET_SHARE_MILEAGE_RECORD = "gps_info.get_share_trip";
        GET_MONITOR_NEW_RECORD = "gps_info.get_real_time_data";
        GET_RANKING = "gps_info.get_ranking";
        SET_DEFAULT_CEHICLE = "mine_car.set_default_car";
        GET_ROUTE_BLACK_PLAY = "gps_info.get_travel_data";
        SIM_CARD_GET_CHARGE_SERIES = "sim_card.get_charge_series";
        SIM_CARD_CREATE_CHARGE_ORDER = "sim_card.create_charge_order";
        SIM_CARD_DO_ALIPAY_VERIFY = "sim_card.do_alipay_verify";
        SIM_CARD_CREATE_INVOICE = "sim_card.create_invoice";
        SIM_CARD_GET_FLOW_BY_SERIAL = "sim_card.get_flow_by_serial";
        CREATE_PICK_ME_UP_MISSION = "pickmeup.create";
        GET_PICK_ME_UP_MISSION_RECORD = "pickmeup.list";
        MODIFY_MISSION_INFO = "pickmeup.update";
        DELETE_MISSION_INFO = "pickmeup.delete";
    }

    public String getCode() {
        return this.code;
    }

    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public List<InterfaceUrl> getUrlList() {
        return this.urlList;
    }

    public void setUrlList(List<InterfaceUrl> urlList) {
        this.urlList = urlList;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMsg() {
        return this.msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }
}
