package com.ifoer.entity;

import android.app.Activity;
import android.content.Context;
import android.os.Environment;
import android.util.DisplayMetrics;
import com.car.result.LoginResult;
import com.ifoer.expedition.BluetoothChat.BluetoothChatService;
import com.ifoer.expeditionphone.BaseActivity;
import com.ifoer.util.CarDiagnoseBridge;
import com.ifoer.util.Files;
import com.ifoer.util.MyHttpException;
import com.ifoer.util.MySharedPreferences;
import com.tencent.mm.sdk.platformtools.FilePathGenerator;
import java.util.ArrayList;
import java.util.HashMap;
import org.xbill.DNS.Flags;
import org.xbill.DNS.WKSRecord.Service;

public class Constant {
    public static final String ACTION = "action";
    public static final String ACTION_REGEX = "action=";
    public static String ADDRESS = null;
    public static final String ALIPAY_WEBSITE_PATH = "http://mycar.x431.com/services/alipay/enterMobileAlipay.action?orderSn=";
    public static String APK_PATH = null;
    public static final String APP_ID = "921";
    public static final String APP_VERSION = "1.0";
    public static final String AUTHENTICATE = "authenticate";
    public static String CAR_PATH = null;
    public static final int CHARGE_SECCUSS = 808;
    public static final int CHECK_UPDATE_SUCCESS = 807;
    public static String CONFIG_WEBSITE_FILE_PATH = null;
    public static String CONFIG_WEBSITE_PATH = null;
    public static byte[] CombinationMenu = null;
    public static String DOC_UNZIP = null;
    public static String DOC_ZIP = null;
    public static String DOWBIN_UPGRADE_PATH = null;
    public static String DST_FILE = null;
    public static final int ERROR_CODE = 805;
    public static final int ERROR_GET_DATA_FAILED = 806;
    public static final int ERROR_NETWORK = 803;
    public static final int ERROR_SERVER = 804;
    public static final String EXPIRED_REMIND = "expired_remind";
    public static final int GET_APK_VERSION = 912;
    public static final int GET_CARD_INFO_SUCCESS = 810;
    public static final int GET_FIRM_VERSION = 913;
    public static final int GIVEUP_FIRM_UPGRADE = 917;
    public static final String GOOGLE_GEOCODE_PATH = "http://maps.google.com/maps/api/geocode/json";
    public static final int GRAPHIC_ICON_NUM_CHANGE = 911;
    public static int GRAPHIC_X = 0;
    public static final int HAS_UPGRADER_FIRM = 915;
    public static final String IDENTITY_M = "0";
    public static final String IDENTITY_S = "1";
    public static final String LANG = "Lang";
    public static String LOCAL_BASE_PATH = null;
    public static final String LOCAL_DIAG = "0";
    public static String LOCAL_SERIALNO_PATH = null;
    public static final int LOGIN_SUCCESS = 802;
    public static final int MESSAGE_BULETOOTH_WAIT = 123;
    public static final int MESSAGE_CLOSE_PROSSGER = 103;
    public static final int MESSAGE_CONNECT_BLUETOOTH = 102;
    public static final int MESSAGE_CONNECT_WAITTING = 116;
    public static final int MESSAGE_DOWNLOADLEN = 119;
    public static final int MESSAGE_FAIL_REQUST = 127;
    public static final int MESSAGE_LACKSOFT = 121;
    public static final int MESSAGE_LOSS_PACKAGE = 128;
    public static final int MESSAGE_PDFFAIL = 131;
    public static final int MESSAGE_RCU_RESURE = 115;
    public static final int MESSAGE_RCU_STATE00 = 104;
    public static final int MESSAGE_RCU_STATE01 = 105;
    public static final int MESSAGE_RCU_STATE02 = 106;
    public static final int MESSAGE_RCU_STATE03 = 107;
    public static final int MESSAGE_RCU_STATE04 = 108;
    public static final int MESSAGE_RCU_STATE05 = 109;
    public static final int MESSAGE_RCU_STATE06 = 110;
    public static final int MESSAGE_RCU_STATE07 = 111;
    public static final int MESSAGE_RCU_STATE08 = 112;
    public static final int MESSAGE_RCU_STATE09 = 113;
    public static final int MESSAGE_RCU_STATE0A = 114;
    public static final int MESSAGE_RCU_STATE0B = 129;
    public static final int MESSAGE_RCU_STATE0C = 130;
    public static final int MESSAGE_RCU_STATE0D = 134;
    public static final int MESSAGE_RECONNECT_BLUETOOTH = 135;
    public static final int MESSAGE_RESET_BLUETOOTH = 101;
    public static final int MESSAGE_SAYGOODBYE = 120;
    public static final int MESSAGE_SEND_PDFFILE = 125;
    public static final int MESSAGE_SET_CARMSG = 126;
    public static final int MESSAGE_START_RCU = 100;
    public static final int MESSAGE_STOPIMLINK = 117;
    public static final int MESSAGE_STOP_CONNECT = 118;
    public static final int MESSAGE_TOAST_SHOULDSELECT = 133;
    public static final int MESSAGE_WAITCONNECT = 122;
    public static final int MESSAGE_WAITPROGRESS = 132;
    public static final int MESSAGE_WAIT_PDFCREATE = 124;
    public static final String MYCAR_WEBSERVICE_URL = "http://mycar.x431.com/services/";
    public static final int NEED_BUY = 809;
    public static final int NEXT_PAGE_AVAILABLE = 998;
    public static final int NEXT_PAGE_UNAVAILABLE = 997;
    public static String OBD2_EN_GGP_PATH = null;
    public static String OBD2_EN_GGP_PATH_OLD = null;
    public static final int PAYPAL_INIT_SUCCESS = 2000;
    public static String PAYPAL_PATH = null;
    public static final String PAYPAL_WEBSITE_PATH = "http://mycar.x431.com/services/paypal/enterMobilePaypal.action?orderSn=";
    public static final int PRE_PAGE_AVAILABLE = 996;
    public static final int PRE_PAGE_UNAVAILABLE = 995;
    public static String PRODUCT_TYPE = null;
    public static final String REMOTE_DIAG = "1";
    public static String SDCARD_IMAGES_PATH = null;
    public static final int SETVICE_ABNORMAL = 801;
    public static String STORE_PATH = null;
    public static int ScreenHeight = 0;
    public static int ScreenWidth = 0;
    public static final String THEME = "Theme";
    public static final int TIME_OUT = 800;
    public static final String UC_WEBSERVICE_URL = "http://uc.x431.com/services/";
    public static String UNZIP_PATH = null;
    public static final int UPGRADER_FIRM_FAILED = 916;
    public static String UPLOAD_UNZIP_PATH = null;
    public static String UPLOAD_ZIP_PATH = null;
    public static final String USER_PUBLIC_ID = "USER_PUBLIC_ID";
    public static final String USER_PUBLIC_NAME = "USER_PUBLIC_NAME";
    public static final String WEBSERVICE_NAMESPACE = "http://www.x431.com";
    public static final String WEBSERVICE_SOAPACION = "";
    public static byte[] activeNextCode = null;
    public static String apkLocalVersion = null;
    public static String apkNetWorkVersion = null;
    public static String apkVersionDetailId = null;
    public static final String assestsPath;
    public static boolean bBasicFlag = false;
    public static boolean bOpenFlag = false;
    public static CarDiagnoseBridge bridge = null;
    public static String buildStr = null;
    public static byte[] continueObtain = null;
    public static byte[] continueSpecia = null;
    public static int currentPage = 0;
    public static boolean exsitApp = false;
    public static byte[] feedback = null;
    public static String firmDetailId = null;
    public static String firmLocalVer = null;
    public static String firmNetVer = null;
    public static double geoLat = 0.0d;
    public static double geoLng = 0.0d;
    public static int graphPlayMode = 0;
    public static boolean hasDestroy = false;
    public static boolean hasExucet = false;
    public static boolean hasSetHigh = false;
    public static final String iniPath;
    public static boolean isDataStreamBack = false;
    public static boolean isDataStreamChange = false;
    public static boolean isDemo = false;
    public static boolean isLANDROVER_DEMO = false;
    public static boolean isReset = false;
    public static boolean isSanmu = false;
    public static boolean isVin = false;
    public static String itemContent = null;
    public static String language = null;
    public static LoginResult loginResult = null;
    public static BluetoothChatService mChatService = null;
    public static boolean mIfrefreshXStrat = false;
    public static double mLat = 0.0d;
    public static double mLon = 0.0d;
    public static int model = 0;
    public static boolean needExistDownLoad = false;
    public static final boolean needLog = false;
    public static boolean needWait = false;
    public static final byte[] noButton;
    public static final byte[] noInterruptStreamCode;
    public static byte[] noWaitMessageButton = null;
    public static int pageType = 0;
    public static String path = null;
    public static final String pdfPath;
    public static byte[] previousMenu = null;
    public static byte[] progressbarBox = null;
    public static boolean resureFlag = false;
    public static int resureResult = 0;
    public static byte[] spt_data_stream = null;
    public static byte[] spt_data_stream_button = null;
    public static int spt_datastream_id_ex_page = 0;
    public static ArrayList<Integer> streamIsSelectedList = null;
    public static byte[] streamNextCode = null;
    public static HashMap<Integer, Integer> streamSelectHashMap = null;
    public static int streamSelectHashMap_totle = 0;
    public static boolean upgradeAPk = false;
    public static boolean upgradeFirm = false;
    public static final String urlBusiness = "http://mycar.x431.com/";
    public static final String urlBusinessDownLoad = "http://mycardl.x431.com/";
    public static final String urlUser = "http://uc.x431.com/";

    static {
        LOCAL_BASE_PATH = Environment.getExternalStorageDirectory() + "/cnlaunch/";
        buildStr = "Build:201311209.133825 \u00a92013 ";
        CONFIG_WEBSITE_PATH = "http://base.api.dbscar.com";
        CONFIG_WEBSITE_FILE_PATH = "http://file.api.dbscar.com";
        isDataStreamBack = needLog;
        isDataStreamChange = needLog;
        OBD2_EN_GGP_PATH_OLD = WEBSERVICE_SOAPACION;
        OBD2_EN_GGP_PATH = WEBSERVICE_SOAPACION;
        hasDestroy = needLog;
        needWait = needLog;
        hasExucet = needLog;
        feedback = null;
        previousMenu = new byte[]{(byte) -1, (byte) -1};
        continueObtain = new byte[1];
        streamNextCode = new byte[1];
        noInterruptStreamCode = new byte[1];
        exsitApp = needLog;
        activeNextCode = new byte[]{(byte) -1};
        noButton = new byte[]{(byte) -1};
        progressbarBox = new byte[1];
        continueSpecia = new byte[]{(byte) -1};
        byte[] bArr = new byte[9];
        bArr[3] = Flags.CD;
        bArr[5] = (byte) 3;
        bArr[6] = (byte) -1;
        bArr[7] = (byte) -1;
        bArr[8] = (byte) -16;
        spt_data_stream = bArr;
        spt_data_stream_button = new byte[1];
        noWaitMessageButton = new byte[1];
        path = WEBSERVICE_SOAPACION;
        model = 0;
        geoLat = 0.0d;
        geoLng = 0.0d;
        language = "zh-CN";
        ADDRESS = WEBSERVICE_SOAPACION;
        mChatService = null;
        mLat = 0.0d;
        mLon = 0.0d;
        graphPlayMode = 0;
        currentPage = 0;
        streamSelectHashMap_totle = 5;
        streamIsSelectedList = new ArrayList();
        CombinationMenu = new byte[2];
        streamSelectHashMap = new HashMap();
        spt_datastream_id_ex_page = -1;
        apkVersionDetailId = WEBSERVICE_SOAPACION;
        firmDetailId = WEBSERVICE_SOAPACION;
        upgradeAPk = needLog;
        upgradeFirm = needLog;
        needExistDownLoad = needLog;
        bBasicFlag = needLog;
        bOpenFlag = needLog;
        GRAPHIC_X = MESSAGE_START_RCU;
        mIfrefreshXStrat = needLog;
        isVin = needLog;
        LOCAL_SERIALNO_PATH = getDefaultExternalStoragePath() + "/cnlaunch/";
        PRODUCT_TYPE = "CRP229";
        SDCARD_IMAGES_PATH = LOCAL_SERIALNO_PATH + "/Images/";
        DOWBIN_UPGRADE_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/newestDownload/Diagnostic/Configure/Download/";
        PAYPAL_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/paypal/";
        UPLOAD_ZIP_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/zipFile/";
        APK_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + FilePathGenerator.ANDROID_DIR_SEP;
        UPLOAD_UNZIP_PATH = LOCAL_SERIALNO_PATH + "/cnlaunch/" + FilePathGenerator.ANDROID_DIR_SEP;
        CAR_PATH = LOCAL_SERIALNO_PATH + "/DIAGNOSTIC/VEHICLES/";
        DOC_ZIP = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/docZip/";
        DOC_UNZIP = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + FilePathGenerator.ANDROID_DIR_SEP + Files.getLanguage() + FilePathGenerator.ANDROID_DIR_SEP;
        STORE_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/downloadZip/";
        UNZIP_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/newestDownload/";
        DST_FILE = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/images/";
        assestsPath = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/assets/";
        pdfPath = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + FilePathGenerator.ANDROID_DIR_SEP;
        iniPath = LOCAL_SERIALNO_PATH + "car" + "/assets/";
        isDemo = needLog;
        isSanmu = needLog;
        isReset = needLog;
        hasSetHigh = needLog;
        isLANDROVER_DEMO = needLog;
        pageType = 0;
        ScreenWidth = 0;
        ScreenHeight = 0;
        resureResult = 1;
        resureFlag = true;
        itemContent = WEBSERVICE_SOAPACION;
        loginResult = null;
    }

    public static final String getDefaultExternalStoragePath() {
        String externPath = Environment.getExternalStorageDirectory().getPath();
        String phonePath = externPath;
        String state = Environment.getExternalStorageState();
        if (!Environment.isExternalStorageRemovable()) {
            return externPath;
        }
        if (BaseActivity.mContexts != null) {
            String[] paths = new StorageList(BaseActivity.mContexts).getVolumePaths();
            if (paths.length > 1) {
                phonePath = paths[1];
            }
        }
        return phonePath;
    }

    public static final String[] getDefaultExternalStoragePathList() {
        String[] paths = new String[]{WEBSERVICE_SOAPACION};
        if (!Environment.isExternalStorageRemovable() || BaseActivity.mContexts == null) {
            return paths;
        }
        return new StorageList(BaseActivity.mContexts).getVolumePaths();
    }

    public static final void referValue() {
        LOCAL_SERIALNO_PATH = getDefaultExternalStoragePath() + "/cnlaunch/";
        PRODUCT_TYPE = MySharedPreferences.getStringValue(BaseActivity.mContexts, "SOFT_PRODUCT_TYPE");
        SDCARD_IMAGES_PATH = LOCAL_SERIALNO_PATH + "/Images/";
        DOWBIN_UPGRADE_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/newestDownload/Diagnostic/Configure/Download/";
        PAYPAL_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/paypal/";
        UPLOAD_ZIP_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/zipFile/";
        UPLOAD_UNZIP_PATH = LOCAL_SERIALNO_PATH + "/cnlaunch/" + FilePathGenerator.ANDROID_DIR_SEP;
        CAR_PATH = LOCAL_SERIALNO_PATH + "/DIAGNOSTIC/VEHICLES/";
        DOC_ZIP = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/docZip/";
        DOC_UNZIP = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + FilePathGenerator.ANDROID_DIR_SEP + Files.getLanguage() + FilePathGenerator.ANDROID_DIR_SEP;
        STORE_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/downloadZip/";
        UNZIP_PATH = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/newestDownload/";
        DST_FILE = LOCAL_SERIALNO_PATH + PRODUCT_TYPE + "/images/";
    }

    public static void setStreamItemNum(Context mContext) {
        DisplayMetrics dm = new DisplayMetrics();
        ((Activity) mContext).getWindowManager().getDefaultDisplay().getMetrics(dm);
        int contentHeight = ((((dm.heightPixels - 46) - 40) - 30) * 7) / 480;
        int typeint = MySharedPreferences.getIntValue(mContext, "PDT_TYPE");
        if (typeint == Service.SUR_MEAS) {
            streamSelectHashMap_totle = 12;
        } else if (typeint == 215) {
            streamSelectHashMap_totle = contentHeight;
        } else if (typeint == MyHttpException.ERROR_USERNAME_FORM) {
            streamSelectHashMap_totle = 5;
        }
    }
}
