package com.ifoer.entity;

import java.io.Serializable;
import java.util.List;

public class InterfaceConfig implements Serializable {
    public static String ACCOUNT_ADD_AMOUNT = null;
    public static String ACCOUNT_GET_DATA = null;
    public static String ACCOUNT_MULIT_ADD = null;
    public static String ALIPAY_MOBILE_ALIPAY = null;
    public static String ALIPAY_NOTIFY_RECEIVER = null;
    public static String AREA_GET_CITY = null;
    public static String AREA_GET_COUNTRY = null;
    public static String AREA_GET_COUNTRY_LIST = null;
    public static String AREA_GET_PROVINCE = null;
    public static String BASIC_URL = null;
    public static String BLACKLIST_ADD = null;
    public static String BLACKLIST_DELETE = null;
    public static String BLACKLIST_IS_BLACKLIST = null;
    public static String BLACKLIST_LIST = null;
    public static String CONFIGURE_CONFIG_CARS = null;
    public static String CONFIGURE_GET_CARS = null;
    public static String CONFIG_URLS = null;
    public static String DATASTREAM_GETDFDATALISTT = null;
    public static String DATASTREAM_GETFAULTCODES = null;
    public static String DATASTREAM_GETOBDDATALIST = null;
    public static String DATASTREAM_GETSYSDATASTREAM = null;
    public static String DIAGSOFT_DOWNLOAD = null;
    public static String DIAG_SOFT = null;
    public static String DIAG_SOFT_BREAK = null;
    public static String DISCOUNT_SHOW_DISCOUNT_INFO = null;
    public static String EXPERT_GET_CARS = null;
    public static String EXPERT_GET_CAR_CLASSIFICATION = null;
    public static String EXPERT_GET_TECH_INFO = null;
    public static String EXPERT_MODIFY_TECH_INFO = null;
    public static String EXPERT_SET_EXPERT_INFO = null;
    public static String FILE_UPLOAD = null;
    public static String FRIEND_ADD = null;
    public static String FRIEND_DELETE = null;
    public static String FRIEND_DETAIL = null;
    public static String FRIEND_ENSURE_ADD = null;
    public static String FRIEND_LIST = null;
    public static String FRIEND_MOBILEBOOK = null;
    public static String FRIEND_RENAME = null;
    public static String FRIEND_WAGGLE = null;
    public static String GET_BASE_INFO = null;
    public static String GET_CONTACT_DATA = null;
    public static String GET_USER_DATA = null;
    public static String GPS_INFO_GET_DATA = null;
    public static String GPS_INFO_GET_HISITORY_POSITION_RECORD = null;
    public static String GPS_INFO_GET_MILEAGE = null;
    public static String GROUP_CREATE = null;
    public static String GROUP_INVITE = null;
    public static String GROUP_KICKED = null;
    public static String GROUP_LIST = null;
    public static String GROUP_MEMBER = null;
    public static String GROUP_MEMBER_DETAIL = null;
    public static String GROUP_QUIT = null;
    public static String GROUP_RELIEVE = null;
    public static String HELP_FEEDBACK = null;
    public static String LBS_CLEAR_LOCATION = null;
    public static String LBS_GET_NEARBY = null;
    public static String LBS_GET_NEARBY_REPAIRSHOP = null;
    public static String LBS_MILEAGE_SERVICE_GET_NEARBY = null;
    public static String LBS_UPDATE_LOCATION = null;
    public static String LOGIN = null;
    public static String MAP_MAP_POINT_RECTIFY = null;
    public static String MINE_CAR_QUERY_CAR_TYPE = null;
    public static String MINE_CAR_QUERY_MINE_CAR_INFO = null;
    public static String MINE_CAR_QUERY_X431_CAR_SERIES = null;
    public static String MINE_CAR_REMOVE_MINE_CAR = null;
    public static String MINE_CAR_SAVE_MINE_CAR_INFO = null;
    public static String MINE_CAR_UPDATE_MINE_CAR = null;
    public static String MODI_PASS = null;
    public static String MY_FOCUSCLIENT_LIST = null;
    public static String MY_REMOTE_USERS_HANDLE = null;
    public static String MY_REMOTE_USERS_LIST = null;
    public static String MY_REMOTE_USERS_REQUSET_TOTAL_COUNT = null;
    public static String MY_TECH_ID = null;
    public static String MY_VIP_LIST = null;
    public static String MY_VIP_USER_INFO = null;
    public static String ONE_KEY_DIAG_BEGIN_ONE_KEY_DIAG_CALC = null;
    public static String ONE_KEY_DIAG_GET_CAR_BRAND_LIST_FOR_DBSCAR_PRO = null;
    public static String ONE_KEY_DIAG_GET_CONFIGED_ALL_INFO = null;
    public static String ONE_KEY_DIAG_GET_CONFIGED_INI_FILE_INFO = null;
    public static String ONE_KEY_DIAG_GET_DIAG_SOFT_MAX_VERSION_BY_SERIAL_NO = null;
    public static String ONE_KEY_DIAG_GET_SOFT_INFO_FOR_DBSCAR_PRO = null;
    public static String ONE_KEY_DIAG_ONE_KEY_DIAG_CALC = null;
    public static String PAYPAL_MOBILE_PAYPAL = null;
    public static String PECCANCY_FIND = null;
    public static String PECCANCY_QUERY = null;
    public static String PECCANCY_TEMP_FIND = null;
    public static String POST_ATTITUDE_ADD = null;
    public static String POST_ATTITUDE_DELETE = null;
    public static String POST_COMMENT_ADD = null;
    public static String POST_COMMENT_DELETE = null;
    public static String POST_CONDITION = null;
    public static String POST_DELETE = null;
    public static String POST_FILE = null;
    public static String POST_FRIENDS = null;
    public static String POST_GET = null;
    public static String POST_GET_BLACKLIST = null;
    public static String POST_GET_CONFIG = null;
    public static String POST_GET_NOSEE = null;
    public static String POST_GET_PUBLIC_EVALUATION = null;
    public static String POST_MESSAGE = null;
    public static String POST_OWNER = null;
    public static String POST_PUBLISH = null;
    public static String POST_SELF = null;
    public static String POST_SET_BLACKLIST = null;
    public static String POST_SET_CONFIG = null;
    public static String POST_SET_NOSEE = null;
    public static String POST_TECHNICIAN = null;
    public static String POST_TRANSPOND = null;
    public static String PRODUCT_PUB_APPLY_BIND_PUB = null;
    public static String PRODUCT_PUB_UNBIND_PUB = null;
    public static String PRODUCT_REGIST_PRODUCT = null;
    public static String PUBACCOUNT_ATTENTION_USERS = null;
    public static String PUBACCOUNT_LIST_PUB = null;
    public static String PUBACCOUNT_LIST_TECH_BYP = null;
    public static String PUBACCOUNT_PID_BYT = null;
    public static String PUBACCOUNT_PUB_DETAIL = null;
    public static String PUBACCOUNT_SEARCH_LIKE = null;
    public static String PUBACCOUNT_USER_ATTENTION_PUB = null;
    public static String PUBACCOUNT_USER_BIND_PUB = null;
    public static String PUBACCOUNT_USER_REMOVE_PUB = null;
    public static String PUBACCOUNT_USER_UNBIND_PUB = null;
    public static String PUBLICSOFT_DOWNLOAD = null;
    public static String PUBLICSOFT_DOWNLOAD_DIAG_SOFT = null;
    public static String PUBLICSOFT_DOWNLOAD_DOCUMENT = null;
    public static String PUBLICSOFT_DOWNLOAD_PHONE_SOFT = null;
    public static String PUBLIC_EXPERT_GET_TECH_DETAIL = null;
    public static String PUBLIC_SOFT = null;
    public static String PUBLIC_SOFT_BREAK = null;
    public static String PUBLIC_USERS = null;
    public static String REGISTER = null;
    public static String REPORT_QUERY = null;
    public static String REPORT_QUERY_DIAGNOSTIC = null;
    public static String REPORT_UPLOAD = null;
    public static String REPORT_UPLOAD_DIAGNOSTIC = null;
    public static String SET_NAME = null;
    public static String SET_PHONE = null;
    public static String UPDATE_CONTACT_DATA = null;
    public static String UPDATE_DATA = null;
    public static String USER_GETPRODUCTS = null;
    public static String USER_GET_BASE_INFO = null;
    public static String USER_GET_COMMON = null;
    public static String USER_GET_CONTACT = null;
    public static String USER_GET_FACE = null;
    public static String USER_GET_HOBBY = null;
    public static String USER_GET_PRICONF = null;
    public static String USER_GET_RAND_HOBBY = null;
    public static String USER_SEARCH = null;
    public static String USER_SET_AREA = null;
    public static String USER_SET_BASE = null;
    public static String USER_SET_CONF = null;
    public static String USER_SET_EXT = null;
    public static String USER_SET_FACE = null;
    public static String USER_UNBIND_EMAIL = null;
    public static String USER_UNBIND_TEL = null;
    public static String VEHICLE_ADD = null;
    public static String VEHICLE_DEL = null;
    public static String VEHICLE_EXAMINATION = null;
    public static String VEHICLE_FIND = null;
    public static String VEHICLE_SET = null;
    public static String VERIFY_REQ_SEND_CODE = null;
    public static String VERIFY_RESET_PASS = null;
    public static String VERIFY_VERIFY_CODE = null;
    public static String VERSION_LAST = null;
    public static String VERSION_LATEST = null;
    public static String WARNING_GET_ITEMS = null;
    public static String WARNING_INFO = null;
    public static String WARNING_SETWARNING = null;
    public static String WARNING_SET_PARAM = null;
    public static String WARNING_STATE = null;
    private static final long serialVersionUID = -4943596269595205500L;
    public static String x431padpublicsoftservice_all;
    private String area;
    private String code;
    private String msg;
    private List<InterfaceUrl> urlList;
    private String version;

    static {
        CONFIG_URLS = "config.urls";
        USER_GET_BASE_INFO = "user.get_base_info";
        USER_SET_BASE = "user.set_base";
        USER_SET_AREA = "user.set_area";
        USER_UNBIND_TEL = "user.unbind_tel";
        USER_UNBIND_EMAIL = "user.unbind_email";
        USER_GET_CONTACT = "user.get_contact";
        USER_SET_EXT = "user.set_ext";
        USER_GET_PRICONF = "user.get_priconf";
        USER_SET_CONF = "user.set_conf";
        USER_GET_COMMON = "user.get_common";
        USER_GET_RAND_HOBBY = "user.get_rand_hobby";
        USER_GET_HOBBY = "user.get_hobby";
        VERIFY_REQ_SEND_CODE = "verify.req_send_code";
        VERIFY_VERIFY_CODE = "verify.verify_code";
        VERIFY_RESET_PASS = "verify.reset_pass";
        MODI_PASS = "userinfo.set_password";
        UPDATE_DATA = "userinfo.update_user";
        GET_USER_DATA = "user.get_user";
        GET_CONTACT_DATA = "user.get_contact";
        UPDATE_CONTACT_DATA = "user.set_ext";
        SET_PHONE = "user.set_base";
        SET_NAME = "user.set_name";
        GET_BASE_INFO = "user.get_base_info_car_logo";
        AREA_GET_COUNTRY_LIST = "area.get_country_list";
        AREA_GET_COUNTRY = "area.get_country";
        AREA_GET_PROVINCE = "area.get_province";
        AREA_GET_CITY = "area.get_city";
        LBS_GET_NEARBY = "lbs.get_nearby";
        LBS_CLEAR_LOCATION = "lbs.clear_location";
        LBS_UPDATE_LOCATION = "lbs.update_location";
        LBS_GET_NEARBY_REPAIRSHOP = "lbs.get_nearby_repairshop";
        LOGIN = "login";
        REGISTER = "register";
        USER_SEARCH = "user.search";
        USER_GET_FACE = "user.get_face";
        USER_SET_FACE = "user.set_face";
        PUBLIC_SOFT = "publicsoft.download";
        DIAG_SOFT = "downloaddiagsoftws.action";
        PUBLIC_SOFT_BREAK = "publicsoft_breakpoint_action";
        DIAG_SOFT_BREAK = "diagsoft_breakpoit_action";
        x431padpublicsoftservice_all = "x431padpublicsoftservice.*";
        FRIEND_ADD = "friend.add";
        FRIEND_ENSURE_ADD = "friend.ensure_add";
        VERSION_LAST = "version.last";
        VERSION_LATEST = "version.latest";
        PUBLIC_USERS = "public.users";
        FILE_UPLOAD = "file.upload";
        GROUP_QUIT = "group.quit";
        GROUP_LIST = "group.list";
        GROUP_CREATE = "group.create";
        GROUP_INVITE = "group.invite";
        GROUP_MEMBER = "group.member";
        GROUP_MEMBER_DETAIL = "group.member_detail";
        GROUP_RELIEVE = "group.relieve";
        GROUP_KICKED = "group.kicked";
        BLACKLIST_ADD = "blacklist.add";
        BLACKLIST_LIST = "blacklist.list";
        BLACKLIST_DELETE = "blacklist.delete";
        BLACKLIST_IS_BLACKLIST = "blacklist.is_blacklist";
        FRIEND_LIST = "friend.list";
        FRIEND_DETAIL = "friend.detail";
        FRIEND_WAGGLE = "friend.waggle";
        FRIEND_DELETE = "friend.delete";
        FRIEND_RENAME = "friend.rename";
        FRIEND_MOBILEBOOK = "friend.mobilebook";
        PUBACCOUNT_USER_ATTENTION_PUB = "pubaccount.user_attention_pub";
        PUBACCOUNT_ATTENTION_USERS = "product_pub.get_attentioned_users";
        PUBACCOUNT_USER_REMOVE_PUB = "pubaccount.user_remove_pub";
        PUBACCOUNT_USER_BIND_PUB = "pubaccount.user_bind_pub";
        PUBACCOUNT_USER_UNBIND_PUB = "pubaccount.user_unbind_pub";
        PRODUCT_PUB_APPLY_BIND_PUB = "product_pub.apply_bind_pub";
        PRODUCT_PUB_UNBIND_PUB = "product_pub.unbind_pub";
        PUBACCOUNT_LIST_PUB = "pubaccount.list_pub";
        PUBACCOUNT_PUB_DETAIL = "pubaccount.pub_detail";
        PUBACCOUNT_SEARCH_LIKE = "pubaccount.search_like";
        PUBACCOUNT_PID_BYT = "pubaccount.pid_byt";
        PUBACCOUNT_LIST_TECH_BYP = "pubaccount.list_tech_byp";
        USER_GETPRODUCTS = "user.getproducts";
        WARNING_GET_ITEMS = "warning.get_items";
        WARNING_SETWARNING = "warning.setwarning";
        WARNING_SET_PARAM = "warning_set_param";
        DATASTREAM_GETFAULTCODES = "datastream.getfaultcodes";
        DATASTREAM_GETSYSDATASTREAM = "datastream.getsysdatastream";
        DATASTREAM_GETOBDDATALIST = "datastream.getobddatalist";
        DATASTREAM_GETDFDATALISTT = "datastream.getdfdatalistt";
        VEHICLE_FIND = "vehicle.find";
        VEHICLE_ADD = "vehicle.add";
        VEHICLE_SET = "vehicle.set";
        VEHICLE_DEL = "vehicle.del";
        PECCANCY_FIND = "peccancy.find";
        ACCOUNT_GET_DATA = "account.get_data";
        ACCOUNT_ADD_AMOUNT = "account.add_amount";
        ACCOUNT_MULIT_ADD = "account.mulit_add";
        VEHICLE_EXAMINATION = "vehicle.examination";
        CONFIGURE_GET_CARS = "configure.get_cars";
        EXPERT_GET_CARS = "public_expert.get_cars";
        EXPERT_GET_TECH_INFO = "public_expert.get_tech_info";
        EXPERT_MODIFY_TECH_INFO = "public_expert.modify_tech_info";
        EXPERT_SET_EXPERT_INFO = "public_expert.set_expert_info";
        EXPERT_GET_CAR_CLASSIFICATION = "public_expert.get_car_classification";
        CONFIGURE_CONFIG_CARS = "configure.config_cars";
        PRODUCT_REGIST_PRODUCT = "product.regist_product";
        ONE_KEY_DIAG_GET_CAR_BRAND_LIST_FOR_DBSCAR_PRO = "one_key_diag.get_car_brand_list_for_dbscar_pro";
        ONE_KEY_DIAG_BEGIN_ONE_KEY_DIAG_CALC = "one_key_diag.begin_one_key_diag_calc";
        ONE_KEY_DIAG_ONE_KEY_DIAG_CALC = "one_key_diag.one_key_diag_calc";
        ONE_KEY_DIAG_GET_SOFT_INFO_FOR_DBSCAR_PRO = "one_key_diag.get_soft_info_for_dbscar_pro";
        ONE_KEY_DIAG_GET_CONFIGED_ALL_INFO = "one_key_diag.get_configed_all_info";
        ONE_KEY_DIAG_GET_CONFIGED_INI_FILE_INFO = "one_key_diag.get_configed_ini_file_info";
        ONE_KEY_DIAG_GET_DIAG_SOFT_MAX_VERSION_BY_SERIAL_NO = "one_key_diag.get_diag_soft_max_version_by_serial_no";
        POST_PUBLISH = "post.publish";
        POST_TRANSPOND = "post.transpond";
        POST_DELETE = "post.delete";
        POST_COMMENT_ADD = "post.comment_add";
        POST_COMMENT_DELETE = "post.comment_delete";
        POST_ATTITUDE_ADD = "post.attitude_add";
        POST_ATTITUDE_DELETE = "post.attitude_delete";
        POST_SELF = "post.self";
        POST_FRIENDS = "post.friends";
        POST_GET = "post.get";
        POST_MESSAGE = "post.message";
        POST_FILE = "post.file";
        POST_OWNER = "post.owner";
        POST_CONDITION = "post.condition";
        POST_TECHNICIAN = "post.technician";
        POST_SET_CONFIG = "post.set_config";
        POST_GET_CONFIG = "post.get_config";
        POST_SET_BLACKLIST = "post.set_blacklist";
        POST_GET_BLACKLIST = "post.get_blacklist";
        POST_SET_NOSEE = "post.set_nosee";
        POST_GET_NOSEE = "post.get_nosee";
        HELP_FEEDBACK = "feedback.post";
        MAP_MAP_POINT_RECTIFY = "map.map_point_rectify";
        MINE_CAR_SAVE_MINE_CAR_INFO = "mine_car.save_mine_car_info";
        MINE_CAR_QUERY_MINE_CAR_INFO = "mine_car.query_mine_car_info";
        MINE_CAR_UPDATE_MINE_CAR = "mine_car.update_mine_car";
        MINE_CAR_REMOVE_MINE_CAR = "mine_car.remove_mine_car";
        MINE_CAR_QUERY_X431_CAR_SERIES = "mine_car.query_x431_car_series";
        GPS_INFO_GET_HISITORY_POSITION_RECORD = "gps_info.get_hisitory_position_record";
        GPS_INFO_GET_MILEAGE = "gps_info.get_mileage";
        LBS_MILEAGE_SERVICE_GET_NEARBY = "lbs_mileage_service.get_nearby";
        GPS_INFO_GET_DATA = "gps_info.get_data";
        REPORT_UPLOAD = "report.upload";
        REPORT_QUERY = "report.query";
        PECCANCY_TEMP_FIND = "peccancy.temp_find";
        PECCANCY_QUERY = "peccancy.query";
        REPORT_UPLOAD_DIAGNOSTIC = "report.upload_diagnostic";
        REPORT_QUERY_DIAGNOSTIC = "report.query_diagnostic";
        MINE_CAR_QUERY_CAR_TYPE = "mine_car.query_car_type";
        MY_VIP_LIST = "product_pub.golo_list_base_info";
        MY_FOCUSCLIENT_LIST = "pubaccount_service.user_attention_pub";
        MY_REMOTE_USERS_LIST = "public_diag.list";
        MY_REMOTE_USERS_REQUSET_TOTAL_COUNT = "public_diag.total";
        MY_REMOTE_USERS_HANDLE = "public_diag.handle";
        MY_TECH_ID = "pubaccount.pid_byt";
        POST_GET_PUBLIC_EVALUATION = "public_expert.get_customer_review_for_tech";
        PUBLIC_EXPERT_GET_TECH_DETAIL = "public_expert.get_tech_detail";
        MY_VIP_USER_INFO = "product_pub.golo_detail_info";
        WARNING_INFO = "client.get_history";
        WARNING_STATE = "client.read";
        DIAGSOFT_DOWNLOAD = "diagsoft.download";
        PUBLICSOFT_DOWNLOAD = "downloadpublicsoftws.action";
        PUBLICSOFT_DOWNLOAD_DOCUMENT = "downloadDocumentWs.action";
        PUBLICSOFT_DOWNLOAD_PHONE_SOFT = "downloadPhoneSoftWs.action";
        PUBLICSOFT_DOWNLOAD_DIAG_SOFT = "downloadDiagSoftWs.action";
        DISCOUNT_SHOW_DISCOUNT_INFO = "showSysDiscountInfo.action";
        PAYPAL_MOBILE_PAYPAL = "enterMobilePaypal.action";
        ALIPAY_MOBILE_ALIPAY = "enterMobileAlipay.action";
        ALIPAY_NOTIFY_RECEIVER = "alipayRSANotifyReceiver.action";
        BASIC_URL = "api.x431";
    }

    public String getCode() {
        return this.code;
    }

    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public List<InterfaceUrl> getUrlList() {
        return this.urlList;
    }

    public void setUrlList(List<InterfaceUrl> urlList) {
        this.urlList = urlList;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMsg() {
        return this.msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }
}
