package com.cnlaunch.framework.common;

public class KeyConstant {
    public static String MY_REMOTE_USERS_CANCEL;
    public static String MY_REMOTE_USERS_HANDLE;
    public static String MY_REMOTE_USERS_PROCESSING;
    public static String MY_REMOTE_USERS_REQUSET_TOTAL_COUNT;
    public static String MY_REMOTE_USERS_RESET;
    public static String account_add_amount;
    public static String account_get_data;
    public static String account_mulit_add;
    public static String alipay_RSATrade;
    public static String alipayservice_all;
    public static String area_get_city;
    public static String area_get_country;
    public static String area_get_country_list;
    public static String area_get_province;
    public static String billservice_all;
    public static String bindingservice_all;
    public static String blacklist_add;
    public static String blacklist_delete;
    public static String blacklist_is_blacklist;
    public static String blacklist_list;
    public static String blacklist_list_car_logo;
    public static String bound_setting_add;
    public static String bound_setting_count_by_serial_no;
    public static String bound_setting_delete;
    public static String bound_setting_get_data;
    public static String bound_setting_update;
    public static String broadcastMessage;
    public static String cancelOrder;
    public static String checkMobilePaypalPayment;
    public static String checkPadIIStatus;
    public static String check_mobile_PaypalPayment;
    public static String client_get_count_list;
    public static String client_get_history;
    public static String client_read;
    public static String cntnewsservice_all;
    public static String collect_add;
    public static String collect_delete;
    public static String collect_file;
    public static String collect_get;
    public static String completePay;
    public static String concernProduct;
    public static String concernproductservice_all;
    public static String config_urls;
    public static String configure_config_cars;
    public static String configure_get_cars;
    public static String createDiagSoftOrder;
    public static String createDiagSoftOrderWithIntegration;
    public static String datastream_getdfdatalist;
    public static String datastream_getfaultcodes;
    public static String datastream_getobddatalist;
    public static String datastream_getsysdatastream;
    public static String db_download;
    public static String diagsoft_breakpoit_action;
    public static String diagsoft_download;
    public static String diagsoft_download_ex;
    public static String diagsoftservice_all;
    public static String drivinginfoservice_all;
    public static String feedback_post;
    public static String file_upload;
    public static String file_video;
    public static String friend_add;
    public static String friend_addf;
    public static String friend_delete;
    public static String friend_detail;
    public static String friend_detail_car_logo;
    public static String friend_ensure_add;
    public static String friend_get_online_status;
    public static String friend_ldetail;
    public static String friend_list;
    public static String friend_list_car_logo;
    public static String friend_mobilebook;
    public static String friend_rename;
    public static String friend_slist;
    public static String friend_valid_addf;
    public static String friend_waggle;
    public static String friend_waggle_car_logo;
    public static String getBinFileMaxVersion;
    public static String getCntSynNews;
    public static String getCntSynUpdateInfo;
    public static String getConcernedProductList;
    public static String getConcernedProductSNInfo;
    public static String getCurrentDrivingInfo;
    public static String getCurrentTypesAndRate;
    public static String getDiagSoftDescResult;
    public static String getDiagSoftDoc;
    public static String getDiagSoftIdList;
    public static String getDiagSoftInfoBySoftId;
    public static String getDiagSoftPrice;
    public static String getNormalBillInfoList;
    public static String getOrderBillPostInfo;
    public static String getPostAddressInfoList;
    public static String getPushMessageDetailContent;
    public static String getPushMessageList;
    public static String getPushMessageListByCC;
    public static String getRegisteredProductsForPad;
    public static String getSeriaNoMaxVersion;
    public static String getShareUrl;
    public static String getSoftPackageInfo;
    public static String getSoftPrice;
    public static String getUserIntegralHistory;
    public static String getUserIntegrals;
    public static String getUserOrderDetailInfo;
    public static String getUserOrderList;
    public static String getValueAddedTaxBillInfoList;
    public static String get_warn_list;
    public static String gps_info_del_trave;
    public static String gps_info_get_car_info;
    public static String gps_info_get_data;
    public static String gps_info_get_data2;
    public static String gps_info_get_device_status;
    public static String gps_info_get_hisitory_position_record;
    public static String gps_info_get_mileage;
    public static String gps_info_get_real_time_location;
    public static String gps_info_get_trip_record;
    public static String group_create;
    public static String group_glist;
    public static String group_group_detail;
    public static String group_invite;
    public static String group_kicked;
    public static String group_list;
    public static String group_member;
    public static String group_member_detail;
    public static String group_quit;
    public static String group_relieve;
    public static String group_save;
    public static String group_update;
    public static String inapppayservice_all;
    public static String iospushservice_all;
    public static String itunesVerify;
    public static String itunes_verify;
    public static String lang_get;
    public static String lbs_clear_location;
    public static String lbs_get_nearby;
    public static String lbs_get_nearby_public;
    public static String lbs_get_nearby_repairshop;
    public static String lbs_mileage_service_get_nearby;
    public static String lbs_update_location;
    public static String locationservice_all;
    public static String log_upload;
    public static String login;
    public static String loginservice_all;
    public static String logout;
    public static String map_get_bd_reverse;
    public static String map_map_point_rectify;
    public static String message_send_message_to_pub;
    public static String mine_car_clear_mine_car_by_serial_no;
    public static String mine_car_get_mine_car_list;
    public static String mine_car_query_auto_logos;
    public static String mine_car_query_car_plate_prefix;
    public static String mine_car_query_car_series_config;
    public static String mine_car_query_car_type;
    public static String mine_car_query_mine_car_info;
    public static String mine_car_query_x431_car_series;
    public static String mine_car_remove_mine_car;
    public static String mine_car_save_mine_car_info;
    public static String mine_car_update_mine_car;
    public static String mine_car_upload_modify_mine_car_image;
    public static String one_key_diag_begin_one_key_diag_calc;
    public static String one_key_diag_get_car_brand_list_for_dbscar_pro;
    public static String one_key_diag_get_configed_all_info;
    public static String one_key_diag_get_configed_ini_file_info;
    public static String one_key_diag_get_diag_soft_max_version_by_serial_no;
    public static String one_key_diag_get_obd_ini_file_info;
    public static String one_key_diag_get_obd_version_detail_id;
    public static String one_key_diag_get_soft_info_for_dbscar_pro;
    public static String one_key_diag_one_key_diag_calc;
    public static String onekeydiag_all;
    public static String paypalservice_all;
    public static String peccancy_find;
    public static String peccancy_query;
    public static String peccancy_temp_find;
    public static String post_attitude_add;
    public static String post_attitude_delete;
    public static String post_comment_add;
    public static String post_comment_delete;
    public static String post_delete;
    public static String post_file;
    public static String post_file_home;
    public static String post_friends;
    public static String post_get;
    public static String post_get_blacklist;
    public static String post_get_config;
    public static String post_get_home;
    public static String post_get_nosee;
    public static String post_hot_city;
    public static String post_message;
    public static String post_pic;
    public static String post_public;
    public static String post_publish;
    public static String post_self;
    public static String post_set_blacklist;
    public static String post_set_config;
    public static String post_set_home;
    public static String post_set_nosee;
    public static String post_transpond;
    public static String product_check_product_update;
    public static String product_pub_apply_bind_pub;
    public static String product_pub_do_with_apply;
    public static String product_pub_get_attentioned_by_userid;
    public static String product_pub_get_attentioned_users;
    public static String product_pub_get_tech_by_sn;
    public static String product_pub_get_vip_list;
    public static String product_pub_golo_detail_info;
    public static String product_pub_golo_list_base_info;
    public static String product_pub_modify_note;
    public static String product_pub_pre_bind;
    public static String product_pub_serial_tech_bind;
    public static String product_pub_unbind_pub;
    public static String product_regist_product;
    public static String product_single_pub_golo_list_base_info;
    public static String product_update_user_role;
    public static String productservice_all;
    public static String pubaccount_apply_expert;
    public static String pubaccount_get_expert;
    public static String pubaccount_list_pub;
    public static String pubaccount_list_tech_byp;
    public static String pubaccount_pid_byt;
    public static String pubaccount_pub_bind_technician;
    public static String pubaccount_pub_bind_user;
    public static String pubaccount_pub_detail;
    public static String pubaccount_pub_unbind_technician;
    public static String pubaccount_public_detail;
    public static String pubaccount_search_like;
    public static String pubaccount_user_attention_pub;
    public static String pubaccount_user_bind_pub;
    public static String pubaccount_user_remove_pub;
    public static String pubaccount_user_unbind_pub;
    public static String public_diag_getdiag;
    public static String public_diag_list;
    public static String public_diag_reserve_list;
    public static String public_expert_add_grade;
    public static String public_expert_add_record;
    public static String public_expert_get_car_classification;
    public static String public_expert_get_cars;
    public static String public_expert_get_customer_review_for_tech;
    public static String public_expert_get_expert;
    public static String public_expert_get_tech_detail;
    public static String public_expert_get_tech_info;
    public static String public_expert_modify_tech_info;
    public static String public_expert_set_expert_info;
    public static String public_expert_set_tech_customer_review;
    public static String public_message_upload_message_material_upload;
    public static String public_soft_get_max_version;
    public static String public_users;
    public static String publicsoft_breakpoint_action;
    public static String publicsoft_download;
    public static String publicsoftservice_all;
    public static String pushMessageForSelectedUser;
    public static String queryAlipayRSATrade;
    public static String queryCntSynNews;
    public static String queryCntSynUpdateInfo;
    public static String queryLatestDiagSofts;
    public static String queryPadIIDiagSofts;
    public static String regDeviceToken;
    public static String reg_user;
    public static String register;
    public static String registerProductForPad;
    public static String remote_service_address;
    public static String report_del_medical_report;
    public static String report_pro_query_list_report;
    public static String report_query;
    public static String report_query_diagnostic;
    public static String report_upload;
    public static String report_upload_diagnostic;
    public static String sendDiagnosticLog;
    public static String send_Client_Version;
    public static String send_Server_Check_Log;
    public static String setBillPostInfo;
    public static String setFaultResolvedFlag;
    public static String setNormalBillInfo;
    public static String setOraderBillPostInfo;
    public static String setValueAddedTaxBillInfo;
    public static String share_alarm_del;
    public static String share_alarm_get;
    public static String share_alarm_set;
    public static String shareservice_all;
    public static String updateCustomerInfo;
    public static String updateMaintanceMillage;
    public static String updateSerialNoVersion;
    public static String userLogin;
    public static String user_get;
    public static String user_get_base_info_car_logo;
    public static String user_get_common;
    public static String user_get_contact;
    public static String user_get_face;
    public static String user_get_hobby;
    public static String user_get_map_conf;
    public static String user_get_priconf;
    public static String user_get_rand_hobby;
    public static String user_get_user;
    public static String user_getproducts;
    public static String user_search;
    public static String user_search_by_car;
    public static String user_search_car_logo;
    public static String user_set_area;
    public static String user_set_base;
    public static String user_set_conf;
    public static String user_set_ext;
    public static String user_set_face;
    public static String user_unbind_email;
    public static String user_unbind_tel;
    public static String userinfo_set_password;
    public static String userinfo_update_user;
    public static String userorderservice_all;
    public static String usersecurityservice_all;
    public static String userservice_all;
    public static String vehicle_add;
    public static String vehicle_del;
    public static String vehicle_examination;
    public static String vehicle_find;
    public static String vehicle_set;
    public static String verify_req_send_code;
    public static String verify_request;
    public static String verify_reset_pass;
    public static String verify_verify_code;
    public static String version_last;
    public static String version_latest;
    public static String warn_msg_read;
    public static String warning_get_history;
    public static String warning_get_items;
    public static String warning_set_param;
    public static String warning_setwarning;
    public static String x431paddiagsoftservice_all;
    public static String x431padpublicsoftservice_all;

    static {
        config_urls = "config.urls";
        user_get_base_info_car_logo = "user.get_base_info_car_logo";
        user_set_base = "user.set_base";
        user_set_area = "user.set_area";
        user_unbind_tel = "user.unbind_tel";
        user_unbind_email = "user.unbind_email";
        user_get_contact = "user.get_contact";
        user_set_ext = "user.set_ext";
        user_get_user = "user.get_user";
        user_get_priconf = "user.get_priconf";
        user_set_conf = "user.set_conf";
        user_get_common = "user.get_common";
        user_get_rand_hobby = "user.get_rand_hobby";
        user_get_hobby = "user.get_hobby";
        user_get_map_conf = "user.get_map_conf";
        userinfo_set_password = "userinfo.set_password";
        verify_req_send_code = "verify.req_send_code";
        verify_request = "verify.request";
        verify_verify_code = "verify.verify_code";
        verify_reset_pass = "verify.reset_pass";
        diagsoft_download = "diagsoft.download";
        area_get_country_list = "area.get_country_list";
        area_get_country = "area.get_country";
        area_get_province = "area.get_province";
        area_get_city = "area.get_city";
        lbs_get_nearby = "lbs.get_nearby";
        lbs_get_nearby_repairshop = "lbs.get_nearby_repairshop";
        lbs_get_nearby_public = "lbs.get_nearby_public";
        lbs_clear_location = "lbs.clear_location";
        lbs_update_location = "lbs.update_location";
        login = "login";
        register = "register";
        reg_user = "reg_user";
        logout = "logout";
        feedback_post = "feedback.post";
        user_search = "user.search";
        user_search_car_logo = "user.search_car_logo";
        user_search_by_car = "user.search_by_car";
        user_get_face = "user.get_face";
        user_set_face = "user.set_face";
        user_get = "user.get";
        friend_add = "friend.add";
        friend_ensure_add = "friend.ensure_add";
        version_last = "version.last";
        version_latest = "version.latest";
        public_users = "public.users";
        file_upload = "file.upload";
        file_video = "file.video";
        lang_get = "lang.get";
        log_upload = "log.upload";
        group_quit = "group.quit";
        group_list = "group.list";
        group_glist = "group.glist";
        group_create = "group.create";
        group_invite = "group.invite";
        group_member = "group.member";
        group_member_detail = "group.member_detail";
        group_relieve = "group.relieve";
        group_kicked = "group.kicked";
        group_update = "group.update";
        group_save = "group.save";
        group_group_detail = "group.group_detail";
        blacklist_add = "blacklist.add";
        blacklist_list = "blacklist.list";
        blacklist_delete = "blacklist.delete";
        blacklist_is_blacklist = "blacklist.is_blacklist";
        blacklist_list_car_logo = "blacklist.list_car_logo";
        friend_addf = "friend.addf";
        friend_valid_addf = "friend.valid_addf";
        friend_slist = "friend.slist";
        friend_list = "friend.list";
        friend_ldetail = "friend.ldetail";
        friend_detail = "friend.detail";
        friend_waggle = "friend.waggle";
        friend_delete = "friend.delete";
        friend_rename = "friend.rename";
        friend_mobilebook = "friend.mobilebook";
        friend_get_online_status = "friend.get_online_status";
        friend_list_car_logo = "friend.list_car_logo";
        friend_detail_car_logo = "friend.detail_car_logo";
        friend_waggle_car_logo = "friend.waggle_car_logo";
        pubaccount_pub_bind_technician = "pubaccount.pub_bind_technician";
        pubaccount_pub_unbind_technician = "pubaccount.pub_unbind_technician";
        pubaccount_user_bind_pub = "pubaccount.user_bind_pub";
        pubaccount_pub_bind_user = "pubaccount.pub_bind_user";
        pubaccount_user_unbind_pub = "pubaccount.user_unbind_pub";
        pubaccount_user_attention_pub = "pubaccount.user_attention_pub";
        pubaccount_list_pub = "pubaccount.list_pub";
        message_send_message_to_pub = "message.send_message_to_pub";
        pubaccount_pub_detail = "pubaccount.pub_detail";
        pubaccount_public_detail = "pubaccount.public_detail";
        pubaccount_user_remove_pub = "pubaccount.user_remove_pub";
        pubaccount_search_like = "pubaccount.search_like";
        pubaccount_pid_byt = "pubaccount.pid_byt";
        pubaccount_list_tech_byp = "pubaccount.list_tech_byp";
        pubaccount_apply_expert = "pubaccount.apply_expert";
        pubaccount_get_expert = "pubaccount.get_expert";
        product_pub_get_vip_list = "product_pub.get_vip_list";
        product_pub_apply_bind_pub = "product_pub.apply_bind_pub";
        product_pub_unbind_pub = "product_pub.unbind_pub";
        product_pub_pre_bind = "product_pub.pre_bind";
        product_pub_golo_list_base_info = "product_pub.golo_list_base_info";
        product_pub_golo_detail_info = "product_pub.golo_detail_info";
        product_pub_do_with_apply = "product_pub.do_with_apply";
        product_pub_modify_note = "product_pub.modify_note";
        product_pub_serial_tech_bind = "product_pub.serial_tech_bind";
        product_pub_get_tech_by_sn = "product_pub.get_tech_by_sn";
        public_expert_get_cars = "public_expert.get_cars";
        public_expert_get_car_classification = "public_expert.get_car_classification";
        public_expert_get_expert = "public_expert.get_expert";
        public_expert_get_tech_info = "public_expert.get_tech_info";
        public_expert_get_tech_detail = "public_expert.get_tech_detail";
        public_expert_set_expert_info = "public_expert.set_expert_info";
        public_expert_modify_tech_info = "public_expert.modify_tech_info";
        public_expert_get_customer_review_for_tech = "public_expert.get_customer_review_for_tech";
        public_expert_set_tech_customer_review = "public_expert.set_tech_customer_review";
        public_expert_add_record = "public_expert.add_record";
        public_expert_add_grade = "public_expert.add_grade";
        user_getproducts = "user.getproducts";
        warning_get_items = "warning.get_items";
        warning_setwarning = "warning.setwarning";
        warning_set_param = "warning.set_param";
        datastream_getfaultcodes = "datastream.getfaultcodes";
        datastream_getsysdatastream = "datastream.getsysdatastream";
        datastream_getobddatalist = "datastream.getobddatalist";
        datastream_getdfdatalist = "datastream.getdfdatalist";
        vehicle_find = "vehicle.find";
        vehicle_add = "vehicle.add";
        vehicle_set = "vehicle.set";
        vehicle_del = "vehicle.del";
        peccancy_find = "peccancy.find";
        peccancy_temp_find = "peccancy.temp_find";
        peccancy_query = "peccancy.query";
        account_get_data = "account.get_data";
        account_add_amount = "account.add_amount";
        account_mulit_add = "account.mulit_add";
        vehicle_examination = "vehicle.examination";
        configure_get_cars = "configure.get_cars";
        configure_config_cars = "configure.config_cars";
        bound_setting_add = "bound_setting.add";
        bound_setting_update = "bound_setting.update";
        bound_setting_delete = "bound_setting.delete";
        bound_setting_count_by_serial_no = "bound_setting.count_by_serial_no";
        bound_setting_get_data = "bound_setting.get_data";
        map_map_point_rectify = "map.map_point_rectify";
        map_get_bd_reverse = "map.get_bd_reverse";
        gps_info_get_hisitory_position_record = "gps_info.get_hisitory_position_record";
        gps_info_get_mileage = "gps_info.get_mileage";
        lbs_mileage_service_get_nearby = "lbs_mileage_service.get_nearby";
        gps_info_get_data = "gps_info.get_data";
        gps_info_get_data2 = "gps_info.get_data2";
        client_get_history = "client.get_history";
        get_warn_list = "product_pub.get_warn_list";
        client_get_count_list = "client.get_count_list";
        client_read = "client.read";
        warn_msg_read = "product_pub.warn_msg_read";
        warning_get_history = "warning.get_history";
        gps_info_get_real_time_location = "gps_info.get_real_time_location";
        gps_info_del_trave = "gps_info.del_trave";
        public_soft_get_max_version = "public_soft.get_max_version";
        gps_info_get_car_info = "gps_info.get_car_info";
        gps_info_get_device_status = "gps_info.get_device_status";
        gps_info_get_trip_record = "gps_info.get_trip_record";
        mine_car_save_mine_car_info = "mine_car.save_mine_car_info";
        mine_car_query_mine_car_info = "mine_car.query_mine_car_info";
        mine_car_get_mine_car_list = "mine_car.get_mine_car_list";
        mine_car_update_mine_car = "mine_car.update_mine_car";
        mine_car_remove_mine_car = "mine_car.remove_mine_car";
        mine_car_query_x431_car_series = "mine_car.query_x431_car_series";
        mine_car_query_car_type = "mine_car.query_car_type";
        mine_car_query_car_plate_prefix = "mine_car.query_car_plate_prefix";
        mine_car_query_car_series_config = "mine_car.query_car_series_config";
        mine_car_clear_mine_car_by_serial_no = "mine_car.clear_mine_car_by_serial_no";
        mine_car_upload_modify_mine_car_image = "mine_car_upload.modify_mine_car_image";
        mine_car_query_auto_logos = "mine_car.query_auto_logos";
        public_message_upload_message_material_upload = "public_message_upload.message_material_upload";
        product_regist_product = "product.regist_product";
        product_check_product_update = "product.check_product_update";
        product_update_user_role = "product.update_user_role";
        one_key_diag_get_car_brand_list_for_dbscar_pro = "one_key_diag.get_car_brand_list_for_dbscar_pro";
        one_key_diag_begin_one_key_diag_calc = "one_key_diag.begin_one_key_diag_calc";
        one_key_diag_one_key_diag_calc = "one_key_diag.one_key_diag_calc";
        one_key_diag_get_soft_info_for_dbscar_pro = "one_key_diag.get_soft_info_for_dbscar_pro";
        one_key_diag_get_configed_all_info = "one_key_diag.get_configed_all_info";
        one_key_diag_get_configed_ini_file_info = "one_key_diag.get_configed_ini_file_info";
        one_key_diag_get_diag_soft_max_version_by_serial_no = "one_key_diag.get_diag_soft_max_version_by_serial_no";
        one_key_diag_get_obd_ini_file_info = "one_key_diag.get_obd_ini_file_info";
        one_key_diag_get_obd_version_detail_id = "one_key_diag.get_obd_version_detail_id";
        report_upload = "report.upload";
        report_query = "report.query";
        report_del_medical_report = "report.del_medical_report";
        report_upload_diagnostic = "report.upload_diagnostic";
        report_query_diagnostic = "report.query_diagnostic";
        share_alarm_set = "share_alarm.set";
        share_alarm_get = "share_alarm.get";
        share_alarm_del = "share_alarm.del";
        post_publish = "post.publish";
        post_transpond = "post.transpond";
        post_delete = "post.delete";
        post_comment_add = "post.comment_add";
        post_comment_delete = "post.comment_delete";
        post_attitude_add = "post.attitude_add";
        post_attitude_delete = "post.attitude_delete";
        post_self = "post.self";
        post_friends = "post.friends";
        post_get = "post.get";
        post_message = "post.message";
        post_file = "post.file";
        post_set_config = "post.set_config";
        post_get_config = "post.get_config";
        post_set_blacklist = "post.set_blacklist";
        post_get_blacklist = "post.get_blacklist";
        post_set_nosee = "post.set_nosee";
        post_get_nosee = "post.get_nosee";
        getSeriaNoMaxVersion = "getSeriaNoMaxVersion";
        updateSerialNoVersion = "updateSerialNoVersion";
        post_public = "post.public";
        post_pic = "post.pic";
        post_set_home = "post.set_home";
        post_get_home = "post.get_home";
        post_file_home = "post.file_home";
        post_hot_city = "post.hot_city";
        collect_add = "collect.add";
        collect_get = "collect.get";
        collect_delete = "collect.delete";
        collect_file = "collect.file";
        onekeydiag_all = "onekeydiag.*";
        db_download = "db.download";
        publicsoft_download = "publicsoft.download";
        publicsoft_breakpoint_action = "publicsoft_breakpoint_action";
        diagsoft_breakpoit_action = "diagsoft_breakpoit_action";
        checkMobilePaypalPayment = "checkMobilePaypalPayment";
        queryCntSynNews = "queryCntSynNews";
        getCntSynNews = "getCntSynNews";
        queryCntSynUpdateInfo = "queryCntSynUpdateInfo";
        getCntSynUpdateInfo = "getCntSynUpdateInfo";
        regDeviceToken = "regDeviceToken";
        concernProduct = "concernProduct";
        updateMaintanceMillage = "updateMaintanceMillage";
        getConcernedProductList = "getConcernedProductList";
        updateCustomerInfo = "updateCustomerInfo";
        getConcernedProductSNInfo = "getConcernedProductSNInfo";
        getPushMessageList = "getPushMessageList";
        getPushMessageDetailContent = "getPushMessageDetailContent";
        setFaultResolvedFlag = "setFaultResolvedFlag";
        broadcastMessage = "broadcastMessage";
        pushMessageForSelectedUser = "pushMessageForSelectedUser";
        getCurrentDrivingInfo = "getCurrentDrivingInfo";
        getPushMessageListByCC = "getPushMessageListByCC";
        userLogin = "userLogin";
        getBinFileMaxVersion = "getBinFileMaxVersion";
        registerProductForPad = "registerProductForPad";
        getRegisteredProductsForPad = "getRegisteredProductsForPad";
        checkPadIIStatus = "checkPadIIStatus";
        getUserIntegrals = "getUserIntegrals";
        getUserIntegralHistory = "getUserIntegralHistory";
        getCurrentTypesAndRate = "getCurrentTypesAndRate";
        getShareUrl = "getShareUrl";
        createDiagSoftOrder = "createDiagSoftOrder";
        cancelOrder = "cancelOrder";
        getUserOrderList = "getUserOrderList";
        getUserOrderDetailInfo = "getUserOrderDetailInfo";
        completePay = "completePay";
        getSoftPackageInfo = "getSoftPackageInfo";
        queryAlipayRSATrade = "queryAlipayRSATrade";
        getSoftPrice = "getSoftPrice";
        getDiagSoftPrice = "getDiagSoftPrice";
        itunesVerify = "itunesVerify";
        createDiagSoftOrderWithIntegration = "createDiagSoftOrderWithIntegration";
        getDiagSoftDoc = "getDiagSoftDoc";
        getDiagSoftDescResult = "getDiagSoftDescResult";
        queryLatestDiagSofts = "queryLatestDiagSofts";
        queryPadIIDiagSofts = "queryPadIIDiagSofts";
        getDiagSoftIdList = "getDiagSoftIdList";
        getDiagSoftInfoBySoftId = "getDiagSoftInfoBySoftId";
        getValueAddedTaxBillInfoList = "getValueAddedTaxBillInfoList";
        setOraderBillPostInfo = "setOraderBillPostInfo";
        setNormalBillInfo = "setNormalBillInfo";
        getNormalBillInfoList = "getNormalBillInfoList";
        setBillPostInfo = "setBillPostInfo";
        setValueAddedTaxBillInfo = "setValueAddedTaxBillInfo";
        getPostAddressInfoList = "getPostAddressInfoList";
        getOrderBillPostInfo = "getOrderBillPostInfo";
        billservice_all = "billservice.*";
        paypalservice_all = "paypalservice.*";
        cntnewsservice_all = "cntnewsservice.*";
        productservice_all = "productservice.*";
        userorderservice_all = "userorderservice.*";
        alipayservice_all = "alipayservice.*";
        iospushservice_all = "iospushservice.*";
        inapppayservice_all = "inapppayservice.*";
        concernproductservice_all = "concernproductservice.*";
        drivinginfoservice_all = "drivinginfoservice.*";
        publicsoftservice_all = "publicsoftservice.*";
        userservice_all = "userservice.*";
        bindingservice_all = "bindingservice.*";
        usersecurityservice_all = "usersecurityservice.*";
        locationservice_all = "locationservice.*";
        loginservice_all = "loginservice.*";
        shareservice_all = "shareservice.*";
        diagsoftservice_all = "diagsoftservice.*";
        x431paddiagsoftservice_all = "x431paddiagsoftservice.*";
        x431padpublicsoftservice_all = "x431padpublicsoftservice.*";
        diagsoft_download_ex = "downloaddiagsoftws.action";
        itunes_verify = "itunesVerify";
        alipay_RSATrade = "queryAlipayRSATrade";
        check_mobile_PaypalPayment = "checkMobilePaypalPayment";
        remote_service_address = "remote_diagnostics_service.get_address";
        product_pub_get_attentioned_users = "product_pub.get_attentioned_users";
        product_pub_get_attentioned_by_userid = "product_pub.get_attentioned_by_userid";
        public_diag_list = "public_diag.list";
        public_diag_getdiag = "public_diag.get_diag";
        product_single_pub_golo_list_base_info = "product_pub.users_by_bind_uid";
        MY_REMOTE_USERS_HANDLE = "public_diag.handle";
        MY_REMOTE_USERS_REQUSET_TOTAL_COUNT = "public_diag.total";
        userinfo_update_user = "userinfo.update_user";
        sendDiagnosticLog = "sendDiagnosticLog";
        send_Server_Check_Log = "sendServerCheckLog";
        public_diag_reserve_list = "public_diag.reserve_list";
        send_Client_Version = "sendClientVersion";
        MY_REMOTE_USERS_CANCEL = "public_diag.cancel";
        MY_REMOTE_USERS_RESET = "public_diag.exception_cancel";
        MY_REMOTE_USERS_PROCESSING = "public_diag.processing";
        report_pro_query_list_report = "report.pro_query_list_report";
    }
}
