package com.ifoer.util;

import com.cnlaunch.x431frame.C0136R;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class CarIcon {
    public static List<List<HashMap<String, Object>>> data() {
        List<List<HashMap<String, Object>>> lists = new ArrayList();
        lists.add(china());
        lists.add(asia());
        lists.add(euro());
        lists.add(america());
        lists.add(special());
        return lists;
    }

    public static List<HashMap<String, Object>> special() {
        List<HashMap<String, Object>> specialList = new ArrayList();
        HashMap hashMap = new HashMap();
        HashMap<String, Object> map = new HashMap();
        map.put("softPackageId", "RESETBRAKE");
        map.put("name", "resetbrake");
        map.put("name_zh", "resetbrake_zh");
        map.put("icon", "icon_eobd2");
        map.put("areaId", Integer.valueOf(5));
        map.put("sname", Integer.valueOf(C0136R.string.resetbrake));
        map.put("sname_zh", "SHACHE");
        specialList.add(map);
        map = new HashMap();
        map.put("softPackageId", "RESETSAS");
        map.put("name", "resetsas");
        map.put("name_zh", "resetsas_zh");
        map.put("icon", "icon_eobd2");
        map.put("areaId", Integer.valueOf(5));
        map.put("sname", Integer.valueOf(C0136R.string.resetsas));
        map.put("sname_zh", "ZHUANXIANGJIAO");
        specialList.add(map);
        map = new HashMap();
        map.put("softPackageId", "RESETOIL");
        map.put("name", "resetoil");
        map.put("name_zh", "resetoil_zh");
        map.put("icon", "icon_eobd2");
        map.put("areaId", Integer.valueOf(5));
        map.put("sname", Integer.valueOf(C0136R.string.resetoil));
        map.put("sname_zh", "JIYOU");
        specialList.add(map);
        map = new HashMap();
        map.put("softPackageId", "RESETBMS");
        map.put("name", "resetbms");
        map.put("name_zh", "resetbms_zh");
        map.put("icon", "icon_eobd2");
        map.put("areaId", Integer.valueOf(5));
        map.put("sname", Integer.valueOf(C0136R.string.resetbms_zh));
        map.put("sname_zh", "RESETBMS");
        specialList.add(map);
        return specialList;
    }

    public static List<HashMap<String, Object>> asia() {
        List<HashMap<String, Object>> asiaList = new ArrayList();
        HashMap hashMap = new HashMap();
        HashMap<String, Object> map = new HashMap();
        map.put("softPackageId", "EOBD2");
        map.put("name", "eobd2");
        map.put("name_zh", "eobd2_cn");
        map.put("icon", "icon_eobd2");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DEMO");
        map.put("name", "demo");
        map.put("name_zh", "demo_zh");
        map.put("icon", "icon_demo");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ACURA");
        map.put("name", "acura");
        map.put("name_zh", "acura_zh");
        map.put("icon", "icon_acura");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.acura));
        map.put("sname_zh", "OUGE");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DAEWOO");
        map.put("name", "daewoo");
        map.put("name_zh", "daewoo_zh");
        map.put("icon", "icon_daewoo");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.daewoo));
        map.put("sname_zh", "DAYU");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DAIHATSU");
        map.put("name", "daihatsu");
        map.put("name_zh", "daihatsu_zh");
        map.put("icon", "icon_daihatsu");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.daihatsu));
        map.put("sname_zh", "DAFA");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HONDA");
        map.put("name", "honda");
        map.put("name_zh", "honda_zh");
        map.put("icon", "icon_honda");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.honda));
        map.put("sname_zh", "BENTIANCHEXI");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HYUNDAI");
        map.put("name", "hyundai");
        map.put("name_zh", "hyundai_zh");
        map.put("icon", "icon_hyundai");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.hyundai));
        map.put("sname_zh", "XIANDAI");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "INFINITI");
        map.put("name", "infiniti");
        map.put("name_zh", "infiniti_zh");
        map.put("icon", "icon_infiniti");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.infiniti));
        map.put("sname_zh", "YINGFEINIDI");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "KIA");
        map.put("name", "kia");
        map.put("name_zh", "kia_zh");
        map.put("icon", "icon_kia");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.kia));
        map.put("sname_zh", "QIYA");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "MARUTI");
        map.put("name", "maruti");
        map.put("name_zh", "maruti_zh");
        map.put("icon", "icon_maruti");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.maruti));
        map.put("sname_zh", "MARUTI");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "MAZDA");
        map.put("name", "mazda");
        map.put("name_zh", "mazda_zh");
        map.put("icon", "icon_mazda");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.mazda));
        map.put("sname_zh", "MAZIDA");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "MITSUBISHI");
        map.put("name", "mitsubishi");
        map.put("name_zh", "mitsubishi_zh");
        map.put("icon", "icon_mitsubishi");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.mitsubishi));
        map.put("sname_zh", "SANLING");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "NISSAN");
        map.put("name", "nissan");
        map.put("name_zh", "nissan_zh");
        map.put("icon", "icon_nissan");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.nissan));
        map.put("sname_zh", "RICHAN");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "PERODUA");
        map.put("name", "perodua");
        map.put("name_zh", "perodua_zh");
        map.put("icon", "icon_perodua");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.perodua));
        map.put("sname_zh", "PERODUA");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "MAHINDRA");
        map.put("name", "mahindra");
        map.put("name_zh", "mahindra_zh");
        map.put("icon", "icon_mahindra");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.mahindra));
        map.put("sname_zh", "mahengda");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SSANGYONG");
        map.put("name", "ssangyong");
        map.put("name_zh", "ssangyong_zh");
        map.put("icon", "icon_ssangyong");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.ssangyong));
        map.put("sname_zh", "SHUANGLONG");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SUBARU");
        map.put("name", "subaru");
        map.put("name_zh", "subaru_zh");
        map.put("icon", "icon_subaru");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.subaru));
        map.put("sname_zh", "SIBALU");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SUZUKI");
        map.put("name", "suzuki");
        map.put("name_zh", "suzuki_zh");
        map.put("icon", "icon_suzuki");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.suzuki));
        map.put("sname_zh", "LINGMU");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "TATA");
        map.put("name", "tata");
        map.put("name_zh", "tata_zh");
        map.put("icon", "icon_tata");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.tata));
        map.put("sname_zh", "TATA");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "TOYOTA");
        map.put("name", "toyota");
        map.put("name_zh", "toyota_zh");
        map.put("icon", "icon_toyota");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.toyota));
        map.put("sname_zh", "FENGTIAN");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "PROTON");
        map.put("name", "proton");
        map.put("name_zh", "proton_zh");
        map.put("icon", "icon_proton");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.proton));
        map.put("sname_zh", "BAOTENG");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "TLISUZU");
        map.put("name", "tlisuzu");
        map.put("name_zh", "tlisuzu_zh");
        map.put("icon", "icon_tlisuzu");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.tlisuzu));
        map.put("sname_zh", "TAIGUOWUSHILING");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "INDONESIADAIHATSU");
        map.put("name", "indonesiadaihatsu");
        map.put("name_zh", "indonesiadaihatsu_zh");
        map.put("icon", "icon_indonesiadaihatsu");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.indonesiadaihatsu));
        map.put("sname_zh", "YINNIDAFA");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JPISUZU");
        map.put("name", "jpisuzu");
        map.put("name_zh", "jpisuzu_zh");
        map.put("icon", "icon_jpisuzu");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.jpisuzu));
        map.put("sname_zh", "WUSHILING");
        asiaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "LEXUS");
        map.put("name", "lexus");
        map.put("name_zh", "lexus_zh");
        map.put("icon", "icon_lexus");
        map.put("areaId", Integer.valueOf(4));
        map.put("sname", Integer.valueOf(C0136R.string.lexus));
        map.put("sname_zh", "LEIKESASI");
        asiaList.add(map);
        return asiaList;
    }

    public static List<HashMap<String, Object>> china() {
        List<HashMap<String, Object>> chinaList = new ArrayList();
        HashMap<String, Object> map = new HashMap();
        map.put("softPackageId", "ALTO");
        map.put("name", "alto");
        map.put("name_zh", "alto_cn");
        map.put("icon", "icon_alto");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.alto));
        map.put("sname_zh", "JIANGNANAOTUO");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FUKANG");
        map.put("name", "df_citroen");
        map.put("name_zh", "df_citroen_cn");
        map.put("icon", "icon_fukang");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.df_citroen));
        map.put("sname_zh", "DONGFENGXUETIELONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DONGFENGFS");
        map.put("name", "dffs");
        map.put("name_zh", "dffs_zh");
        map.put("icon", "icon_qnlhzy");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dffs));
        map.put("sname_zh", "DONGFENGFENGSHEN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "EOBD2");
        map.put("name", "eobd2");
        map.put("name_zh", "eobd2_cn");
        map.put("icon", "icon_eobd");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DEMO");
        map.put("name", "demo");
        map.put("name_zh", "demo_zh");
        map.put("icon", "icon_demo");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HMAZDA");
        map.put("name", "hmazda");
        map.put("name_zh", "hmazda_zh");
        map.put("icon", "icon_haima");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.hmazda));
        map.put("sname_zh", "HAINANMAZIDA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ZHENGZHOUHMAZDA");
        map.put("name", "haimacustomized");
        map.put("name_zh", "haimacustomized_cn");
        map.put("icon", "icon_haima");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.haimacustomized));
        map.put("sname_zh", "HAIMA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "AOKESI");
        map.put("name", "aokesi");
        map.put("name_zh", "aokesi_cn");
        map.put("icon", "icon_aokesi");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.aokesi));
        map.put("sname_zh", "AOKESI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "BAOLONG");
        map.put("name", "baolong");
        map.put("name_zh", "baolong_cn");
        map.put("icon", "icon_baolong");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.baolong));
        map.put("sname_zh", "BAOLONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "BEILV");
        map.put("name", "beilv");
        map.put("name_zh", "beilv_cn");
        map.put("icon", "icon_beilv");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.beilv));
        map.put("sname_zh", "BEILVYUHU");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "BJJEEP");
        map.put("name", "bjjeep");
        map.put("name_zh", "bjjeep_cn");
        map.put("icon", "icon_bjjeep");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.bjjeep));
        map.put("sname_zh", "BEIJINGJIPU");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "BJXD");
        map.put("name", "bjxd");
        map.put("name_zh", "bjxd_cn");
        map.put("icon", "icon_bjxd");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.bjxd));
        map.put("sname_zh", "BEIJINGXIANDAI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "BQZZ");
        map.put("name", "Bqzz");
        map.put("name_zh", "Bqzz_cn");
        map.put("icon", "icon_bqzz");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.Bqzz));
        map.put("sname_zh", "BEIQIZHIZAO");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CALM");
        map.put("name", "ca_suzuki");
        map.put("name_zh", "ca_suzuki_cn");
        map.put("icon", "icon_calm");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.ca_suzuki));
        map.put("sname_zh", "CHANGANLINGMU");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHANGAN");
        map.put("name", "changan");
        map.put("name_zh", "changan_cn");
        map.put("icon", "icon_changan");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.changan));
        map.put("sname_zh", "CHANGANQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHANGANFORD");
        map.put("name", "chinaford");
        map.put("name_zh", "chinaford_cn");
        map.put("icon", "icon_changanford");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.chinaford));
        map.put("sname_zh", "ZHONGGUOFUTE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHANGCHENG");
        map.put("name", "changcheng");
        map.put("name_zh", "changcheng_cn");
        map.put("icon", "icon_changcheng");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.changcheng));
        map.put("sname_zh", "CHANGCHENGQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHANGHE");
        map.put("name", "changhe");
        map.put("name_zh", "changhe_cn");
        map.put("icon", "icon_changhe");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.changhe));
        map.put("sname_zh", "CHANGHEQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHZY");
        map.put("name", "chzy");
        map.put("name_zh", "chzy_cn");
        map.put("icon", "icon_changhe");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.chzy));
        map.put("sname_zh", "CHZY");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHSUZUKI");
        map.put("name", "chsuzuki");
        map.put("name_zh", "chsuzuki_cn");
        map.put("icon", "icon_chsuzuki");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.chsuzuki));
        map.put("sname_zh", "CHANGHELINGMU");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CQISUZU");
        map.put("name", "cqisuzu");
        map.put("name_zh", "cqisuzu_cn");
        map.put("icon", "icon_cqisuzu");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.cqisuzu));
        map.put("sname_zh", "QINGLING");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DADI");
        map.put("name", "dadi");
        map.put("name_zh", "dadi_cn");
        map.put("icon", "icon_cadi");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dadi));
        map.put("sname_zh", "DADIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DFCNG_TY");
        map.put("name", "dfcng_ty");
        map.put("name_zh", "dfcng_ty_cn");
        map.put("icon", "icon_dfcng_ty");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dfcng_ty));
        map.put("sname_zh", "DONGFENGCNG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DFHONDA");
        map.put("name", "dfhonda");
        map.put("name_zh", "dfhonda_cn");
        map.put("icon", "icon_dfhonda");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dfhonda));
        map.put("sname_zh", "DONGFENGBENTIAN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DFNISSAN");
        map.put("name", "dfnissan");
        map.put("name_zh", "dfnissan_cn");
        map.put("icon", "icon_dfnissan");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dfnissan));
        map.put("sname_zh", "DONGFENGRICHAN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DFPEUGEOT");
        map.put("name", "dfpeugeot");
        map.put("name_zh", "dfpeugeot_cn");
        map.put("icon", "icon_dfpeugeot");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dfpeugeot));
        map.put("sname_zh", "DONGFENGBIAOZHI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DFXK");
        map.put("name", "dfxk");
        map.put("name_zh", "dfxk_cn");
        map.put("icon", "icon_dfxk");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dfxk));
        map.put("sname_zh", "DONGFENGXIAOKANG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DONGNAN");
        map.put("name", "dongnan");
        map.put("name_zh", "dongnan_cn");
        map.put("icon", "icon_dongnan");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.dongnan));
        map.put("sname_zh", "DONGNANQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FLYER");
        map.put("name", "byd");
        map.put("name_zh", "byd_cn");
        map.put("icon", "icon_flyer");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.byd));
        map.put("sname_zh", "BIYADIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FUQI");
        map.put("name", "fuqi");
        map.put("name_zh", "fuqi_cn");
        map.put("icon", "icon_fuqi");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.fuqi));
        map.put("sname_zh", "FUQIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FUTIAN");
        map.put("name", "futian");
        map.put("name_zh", "futian_cn");
        map.put("icon", "icon_futian");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.futian));
        map.put("sname_zh", "BEIQIFUTIAN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FZMAZDA");
        map.put("name", "fz_mazid");
        map.put("name_zh", "fz_mazid_cn");
        map.put("icon", "icon_fzmazda");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.fz_mazid));
        map.put("sname_zh", "FUZHOUMAZIDA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FZQICHE");
        map.put("name", "fuzhou");
        map.put("name_zh", "fuzhou_cn");
        map.put("icon", "icon_fzqiche");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.fuzhou));
        map.put("sname_zh", "FUZHOUQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "GZHONDA");
        map.put("name", "gz_honda");
        map.put("name_zh", "gz_honda_cn");
        map.put("icon", "icon_gzhonda");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.gz_honda));
        map.put("sname_zh", "GUANGZHOUBENTIAN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HAFEI");
        map.put("name", "hafei");
        map.put("name_zh", "hafei_cn");
        map.put("icon", "icon_hafei");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.hafei));
        map.put("sname_zh", "HAFEIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HANGTIANMIT_TY");
        map.put("name", "hangtian_mit");
        map.put("name_zh", "hangtian_mit_cn");
        map.put("icon", "icon_hangtianmit_ty");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.hangtian_mit));
        map.put("sname_zh", "HANGTIANSANLING");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HANJIANG");
        map.put("name", "hanjiang");
        map.put("name_zh", "hanjiang_cn");
        map.put("icon", "icon_hanjiang");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.hanjiang));
        map.put("sname_zh", "HANGJIANGQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HBQC");
        map.put("name", "hbqc");
        map.put("name_zh", "hbqc_cn");
        map.put("icon", "icon_hbqc");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.hbqc));
        map.put("sname_zh", "HUABEIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HCBMW");
        map.put("name", "hc_bmw");
        map.put("name_zh", "hc_bmw_cn");
        map.put("icon", "icon_hcbmw");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.hc_bmw));
        map.put("sname_zh", "HUACHENBAOMA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HEIBAO");
        map.put("name", "heibao");
        map.put("name_zh", "heibao_cn");
        map.put("icon", "icon_heibao");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.heibao));
        map.put("sname_zh", "SHANDONGHEIBAO");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HTJT");
        map.put("name", "htjt");
        map.put("name_zh", "htjt_cn");
        map.put("icon", "icon_htjt");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.htjt));
        map.put("sname_zh", "HUATAIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HUACHEN");
        map.put("name", "Brilliance");
        map.put("name_zh", "Brilliance_cn");
        map.put("icon", "icon_huachen");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.Brilliance));
        map.put("sname_zh", "HUACHENQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HUAPU");
        map.put("name", "huapu");
        map.put("name_zh", "huapu_cn");
        map.put("icon", "icon_huapu");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.huapu));
        map.put("sname_zh", "SHANGHAIHUAPU");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HUAYANG");
        map.put("name", "huayang");
        map.put("name_zh", "huayang_cn");
        map.put("icon", "icon_huayang");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.huayang));
        map.put("sname_zh", "HUAYANGQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JIAO");
        map.put("name", "gonow");
        map.put("name_zh", "gonow_cn");
        map.put("icon", "icon_jiao");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.gonow));
        map.put("sname_zh", "JIAOQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JINANYUNBAO");
        map.put("name", "jinganyunbao");
        map.put("name_zh", "jinganyunbao_cn");
        map.put("icon", "icon_jinanyunbao");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.jinganyunbao));
        map.put("sname_zh", "GUANGZHOUJINGANYUNBAO");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JINLONG");
        map.put("name", "king_long");
        map.put("name_zh", "king_long_zh");
        map.put("icon", "icon_jinlong");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.king_long));
        map.put("sname_zh", "XIAMENJINLONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "LIFAN");
        map.put("name", "lifan");
        map.put("name_zh", "lifan_zh");
        map.put("icon", "icon_lifan");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.lifan));
        map.put("sname_zh", "LIFANQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "LIUWEI_TY");
        map.put("name", "liuwei");
        map.put("name_zh", "liuwei_zh");
        map.put("icon", "icon_liuwei_ty");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.liuwei));
        map.put("sname_zh", "LIUZHOUWULING");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "LUFENG");
        map.put("name", "lufeng");
        map.put("name_zh", "lufeng_zh");
        map.put("icon", "icon_lufeng");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.lufeng));
        map.put("sname_zh", "JIANGLINGLUFENG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "MEIYA");
        map.put("name", "meiya");
        map.put("name_zh", "meiya_zh");
        map.put("icon", "icon_meiya");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.meiya));
        map.put("sname_zh", "MEIYAQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SAIBAO");
        map.put("name", "saibao");
        map.put("name_zh", "saibao_zh");
        map.put("icon", "icon_saibao");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.saibao));
        map.put("sname_zh", "SHANGHAISAIBAO");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SAICMG");
        map.put("name", "saic_mg");
        map.put("name_zh", "saic_mg_zh");
        map.put("icon", "icon_saicmg");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.saic_mg));
        map.put("sname_zh", "MINGJUE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SAICROEWE");
        map.put("name", "roewe");
        map.put("name_zh", "roewe_zh");
        map.put("icon", "icon_saicroewe");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.roewe));
        map.put("sname_zh", "SHANGHAILONGWEI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SGM");
        map.put("name", "sh_gm");
        map.put("name_zh", "sh_gm_zh");
        map.put("icon", "icon_sgm");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.sh_gm));
        map.put("sname_zh", "ZHONGGUOTONGYONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SHUANGHUAN");
        map.put("name", "shuanghuan");
        map.put("name_zh", "shuanghuan_zh");
        map.put("icon", "icon_shuanghuan");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.shuanghuan));
        map.put("sname_zh", "SHUANGHUANQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SHVW");
        map.put("name", "sh_vw");
        map.put("name_zh", "sh_vw_zh");
        map.put("icon", "icon_shvw");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.sh_vw));
        map.put("sname_zh", "SHANGHAIDAZHONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "TIANMA");
        map.put("name", "tianma");
        map.put("name_zh", "tianma_zh");
        map.put("icon", "icon_tianma");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.tianma));
        map.put("sname_zh", "TIANMAQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "TIANYE");
        map.put("name", "tianye");
        map.put("name_zh", "tianye_zh");
        map.put("icon", "icon_tianye");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.tianye));
        map.put("sname_zh", "TIANYEQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "TJTOYOTA");
        map.put("name", "china_toyota");
        map.put("name_zh", "china_toyota_cn");
        map.put("icon", "icon_tjtoyota");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.china_toyota));
        map.put("sname_zh", "ZHONGGUOFENGTIAN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "TONGBAO");
        map.put("name", "tongbao");
        map.put("name_zh", "tongbao_zh");
        map.put("icon", "icon_tongbao");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.tongbao));
        map.put("sname_zh", "TONGBAOQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "WANFENG");
        map.put("name", "wanfeng");
        map.put("name_zh", "wanfeng_zh");
        map.put("icon", "icon_wanfeng");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.wanfeng));
        map.put("sname_zh", "WANFENGAOTE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "WANTONG");
        map.put("name", "wantong");
        map.put("name_zh", "wantong_zh");
        map.put("icon", "icon_wantong");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.wantong));
        map.put("sname_zh", "WUHANWANTONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "XGHC");
        map.put("name", "xghc");
        map.put("name_zh", "xghc_zh");
        map.put("icon", "icon_xghc");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.xghc));
        map.put("sname_zh", "XINGUANGHUACHEN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "XINDADI");
        map.put("name", "xindadi");
        map.put("name_zh", "xindadi_zh");
        map.put("icon", "icon_xindadi");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.xindadi));
        map.put("sname_zh", "CHENGDUXINTIANDI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "XINTIANDI");
        map.put("name", "xintiandi");
        map.put("name_zh", "xintiandi_zh");
        map.put("icon", "icon_xintiandi");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.xintiandi));
        map.put("sname_zh", "BEIJINGXINTIANDI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YANGCHENG");
        map.put("name", "gaig");
        map.put("name_zh", "gaig_cn");
        map.put("icon", "icon_yangcheng");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.gaig));
        map.put("sname_zh", "GUANGZHOUYANGCHENGQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YANGZI");
        map.put("name", "yangzi");
        map.put("name_zh", "yangzi_zh");
        map.put("icon", "icon_yangzi");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.yangzi));
        map.put("sname_zh", "YANGZIJITUAN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YIZHONG");
        map.put("name", "yizhong");
        map.put("name_zh", "yizhong_zh");
        map.put("icon", "icon_yizhong");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.yizhong));
        map.put("sname_zh", "QINGDAOYIZHONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YQEF");
        map.put("name", "faw_ef");
        map.put("name_zh", "faw_ef_cn");
        map.put("icon", "icon_yqef");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.faw_ef));
        map.put("sname_zh", "YIQIERFA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHDAIHATSUTY");
        map.put("name", "chdaihatsuty");
        map.put("name_zh", "chdaihatsuty_cn");
        map.put("icon", "icon_chdaihatsu");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.chdaihatsuty));
        map.put("sname_zh", "YIQIDAFA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YQHTTY");
        map.put("name", "faw_ht");
        map.put("name_zh", "faw_ht_cn");
        map.put("icon", "icon_yqhtty");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.faw_ht));
        map.put("sname_zh", "YIQIHONGTA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YQMAZDA");
        map.put("name", "faw_mazda");
        map.put("name_zh", "faw_mazda_cn");
        map.put("icon", "icon_yqmazda");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.faw_mazda));
        map.put("sname_zh", "ZHONGGUOMAZIDA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YQVW");
        map.put("name", "faw_vw");
        map.put("name_zh", "faw_vw_cn");
        map.put("icon", "icon_yqvw");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.faw_vw));
        map.put("sname_zh", "YIQIDAZHONG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YUEDA");
        map.put("name", "df_yueda");
        map.put("name_zh", "df_yueda_cn");
        map.put("icon", "icon_yueda");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.df_yueda));
        map.put("sname_zh", "DONGFENGYUEDAQIYA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YUEJIN");
        map.put("name", "yuejin");
        map.put("name_zh", "yuejin_zh");
        map.put("icon", "icon_yuejin");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.yuejin));
        map.put("sname_zh", "YUEJINQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ZHONGSHUN");
        map.put("name", "polarsun");
        map.put("name_zh", "polarsun_zh");
        map.put("icon", "icon_zhongshun");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.polarsun));
        map.put("sname_zh", "ZHONGSHUNQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ZHONGTAI");
        map.put("name", "zotye");
        map.put("name_zh", "zotye_zh");
        map.put("icon", "icon_zhongtai");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.zotye));
        map.put("sname_zh", "ZHONGTAIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ZHONGXING");
        map.put("name", "zhongxing");
        map.put("name_zh", "zhongxing_zh");
        map.put("icon", "icon_zhongxing");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.zhongxing));
        map.put("sname_zh", "ZHONGXINQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ZZNISSAN");
        map.put("name", "zz_nissan");
        map.put("name_zh", "zz_nissan_zh");
        map.put("icon", "icon_zznissan");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.zz_nissan));
        map.put("sname_zh", "ZHENZHOURICHAN");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JIANGHUAI");
        map.put("name", "refine");
        map.put("name_zh", "refine_zh");
        map.put("icon", "icon_jianghuai");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.refine));
        map.put("sname_zh", "JIANGHUAIRUIFENG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JINCHENG");
        map.put("name", "jincheng");
        map.put("name_zh", "jincheng_zh");
        map.put("icon", "icon_jincheng");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.jincheng));
        map.put("sname_zh", "QINGHUANGDAOJINCHENG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "Xinkai");
        map.put("name", "xinkai");
        map.put("name_zh", "xinkai_zh");
        map.put("icon", "icon_xinkai");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.xinkai));
        map.put("sname_zh", "XINKAIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YOUNGLOTUS");
        map.put("name", "qnlh");
        map.put("name_zh", "qnlh_cn");
        map.put("icon", "icon_qingnianlianhua");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.qnlh));
        map.put("sname_zh", "QINGNIANLIANHUA");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "NJFIAT");
        map.put("name", "nanjing_fiat");
        map.put("name_zh", "nanjing_fiat_zh");
        map.put("icon", "icon_fiat");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.nanjing_fiat));
        map.put("sname_zh", "NANJINGFEIYATE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHANGFENG");
        map.put("name", "changfeng");
        map.put("name_zh", "changfeng_cn");
        map.put("icon", "icon_changfeng");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.changfeng));
        map.put("sname_zh", "CHANGFENGLIEBAO");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "HAOQING");
        map.put("name", "geely");
        map.put("name_zh", "geely_cn");
        map.put("icon", "icon_geely");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.geely));
        map.put("sname_zh", "JILIQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "XIALI");
        map.put("name", "xiali");
        map.put("name_zh", "xiali_cn");
        map.put("icon", "icon_xiali");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.xiali));
        map.put("sname_zh", "TIANJINYIQI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JIQING");
        map.put("name", "jiqing");
        map.put("name_zh", "jiqing_cn");
        map.put("icon", "icon_xiali");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.jiqing));
        map.put("sname_zh", "YIQIJIQING");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "QIRUI_TY");
        map.put("name", "chery");
        map.put("name_zh", "chery_cn");
        map.put("icon", "icon_qirui");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.chery));
        map.put("sname_zh", "QIRUIJIAOCHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DFFX");
        map.put("name", "fengxing");
        map.put("name_zh", "fengxing_cn");
        map.put("icon", "icon_dongfengfs");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.fengxing));
        map.put("sname_zh", "DONGFENGFENGXING");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "NJXYTTY");
        map.put("name", "nac_soyat");
        map.put("name_zh", "nac_soyat_cn");
        map.put("icon", "icon_njxyt");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.nac_soyat));
        map.put("sname_zh", "NANQIXINYATU");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "NJYWKTY");
        map.put("name", "ineco_nanjing");
        map.put("name_zh", "ineco_nanjing_cn");
        map.put("icon", "icon_njywk");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.ineco_nanjing));
        map.put("sname_zh", "NANJINGYIWEIKE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SHUGUANG");
        map.put("name", "shuguang");
        map.put("name_zh", "shuguang_cn");
        map.put("icon", "icon_shuguangzy");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.shuguang));
        map.put("sname_zh", "DONGDANSHUGUANG");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SPARK_TY");
        map.put("name", "spark");
        map.put("name_zh", "spark_cn");
        map.put("icon", "icon_spark");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.spark));
        map.put("sname_zh", "XUEFOLAI");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JACTY");
        map.put("name", "jacty");
        map.put("name_zh", "jacty_cn");
        map.put("icon", "icon_jac");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.jacty));
        map.put("sname_zh", "JIANGHUAIJIAOCHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "YQJC");
        map.put("name", "yqjc");
        map.put("name_zh", "yqjc_cn");
        map.put("icon", "icon_yqjc");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.yqjc));
        map.put("sname_zh", "YIQIJIAOCHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ISUZU");
        map.put("name", "isuzu");
        map.put("name_zh", "isuzu_cn");
        map.put("icon", "icon_isuzu");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.isuzu));
        map.put("sname_zh", "JIANGLINGQICHE");
        chinaList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FUDI");
        map.put("name", "fudizy");
        map.put("name_zh", "fudizy_cn");
        map.put("icon", "icon_fudizy");
        map.put("areaId", Integer.valueOf(2));
        map.put("sname", Integer.valueOf(C0136R.string.fudizy));
        map.put("sname_zh", "FUDI");
        chinaList.add(map);
        return chinaList;
    }

    public static List<HashMap<String, Object>> euro() {
        List<HashMap<String, Object>> euroList = new ArrayList();
        HashMap hashMap = new HashMap();
        HashMap<String, Object> map = new HashMap();
        map.put("softPackageId", "EOBD2");
        map.put("name", "eobd2");
        map.put("name_zh", "eobd2_cn");
        map.put("icon", "icon_eobd2");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DEMO");
        map.put("name", "demo");
        map.put("name_zh", "demo_zh");
        map.put("icon", "icon_demo");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "AUDI");
        map.put("name", "audi");
        map.put("name_zh", "audi_zh");
        map.put("icon", "icon_audi");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.audi));
        map.put("sname_zh", "AODI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "VAUXHALL");
        map.put("name", "vauxhall");
        map.put("name_zh", "vauxhall_zh");
        map.put("icon", "icon_vauxhall");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.vauxhall));
        map.put("sname_zh", "WOKESIHAOER");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "BENZ");
        map.put("name", "benz");
        map.put("name_zh", "benz_zh");
        map.put("icon", "icon_benz");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.benz));
        map.put("sname_zh", "BENCHI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "BMW");
        map.put("name", "bmw");
        map.put("name_zh", "bmw_zh");
        map.put("icon", "icon_bmw");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.bmw));
        map.put("sname_zh", "BAOMACHEXI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "CITROEN");
        map.put("name", "citroen");
        map.put("name_zh", "citroen_zh");
        map.put("icon", "icon_citroen");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.citroen));
        map.put("sname_zh", "XUETIANLONG");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "DACIA");
        map.put("name", "dacia");
        map.put("name_zh", "dacia_zh");
        map.put("icon", "icon_dacia");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.dacia));
        map.put("sname_zh", "DAXIYA");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "EUROFORD");
        map.put("name", "ford");
        map.put("name_zh", "ford_zh");
        map.put("icon", "icon_euroford");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.ford));
        map.put("sname_zh", "OUZHOUFUTE");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "FIAT");
        map.put("name", "fiat");
        map.put("name_zh", "fiat_zh");
        map.put("icon", "icon_fiat");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.fiat));
        map.put("sname_zh", "FEIYATECHEXI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "GMSA");
        map.put("name", "gmsa");
        map.put("name_zh", "gmsa_zh");
        map.put("icon", "icon_gmsa");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.gmsa));
        map.put("sname_zh", "NANFEIOUBAO");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "JAGUAR");
        map.put("name", "jaguar");
        map.put("name_zh", "jaguar_zh");
        map.put("icon", "icon_jaguar");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.jaguar));
        map.put("sname_zh", "JIEBAO");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "LANCIA");
        map.put("name", "lancia");
        map.put("name_zh", "lancia_zh");
        map.put("icon", "icon_lancia");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.lancia));
        map.put("sname_zh", "LANQIYA");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "LANDROVER");
        map.put("name", "land_rover");
        map.put("name_zh", "land_rover_zh");
        map.put("icon", "icon_landrover");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.land_rover));
        map.put("sname_zh", "LUHU");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "MINI");
        map.put("name", "mini");
        map.put("name_zh", "mini_zh");
        map.put("icon", "icon_mini");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.mini));
        map.put("sname_zh", "MINI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "OPEL");
        map.put("name", "opel");
        map.put("name_zh", "opel_zh");
        map.put("icon", "icon_opel");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.opel));
        map.put("sname_zh", "OUBAOCHEXI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "PEUGEOT");
        map.put("name", "peugeot");
        map.put("name_zh", "peugeot_zh");
        map.put("icon", "icon_peugeot");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.peugeot));
        map.put("sname_zh", "BIAOZHI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "RENAULT");
        map.put("name", "renault");
        map.put("name_zh", "renault_zh");
        map.put("icon", "icon_renault");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.renault));
        map.put("sname_zh", "LEINUO");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ROMEO");
        map.put("name", "romeo");
        map.put("name_zh", "romeo_zh");
        map.put("icon", "icon_romeo");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.romeo));
        map.put("sname_zh", "LUOMIOU");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "ROVER");
        map.put("name", "rover");
        map.put("name_zh", "rover_zh");
        map.put("icon", "icon_rover");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.rover));
        map.put("sname_zh", "LUOFU");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SAAB");
        map.put("name", "saab");
        map.put("name_zh", "saab_zh");
        map.put("icon", "icon_saab");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.saab));
        map.put("sname_zh", "SABO");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SEAT");
        map.put("name", "seat");
        map.put("name_zh", "seat_zh");
        map.put("icon", "icon_seat");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.seat));
        map.put("sname_zh", "XITE");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SKODA");
        map.put("name", "skoda");
        map.put("name_zh", "skoda_zh");
        map.put("icon", "icon_skoda");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.skoda));
        map.put("sname_zh", "SIKEDA");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SMART");
        map.put("name", "smart");
        map.put("name_zh", "smart_zh");
        map.put("icon", "icon_smart");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.smart));
        map.put("sname_zh", "JINGLING");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "SPRINTER");
        map.put("name", "sprinter");
        map.put("name_zh", "sprinter_zh");
        map.put("icon", "icon_sprinter");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.sprinter));
        map.put("sname_zh", "BENCHISHANWUCHE");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "VAZ");
        map.put("name", "vaz");
        map.put("name_zh", "vaz_zh");
        map.put("icon", "icon_vaz");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.vaz));
        map.put("sname_zh", "VAZ");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "VOLVO");
        map.put("name", "volvo");
        map.put("name_zh", "volvo_zh");
        map.put("icon", "icon_volvo");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.volvo));
        map.put("sname_zh", "WOERWOCHEXI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "VW");
        map.put("name", "vw");
        map.put("name_zh", "vw_zh");
        map.put("icon", "icon_vw");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.vw));
        map.put("sname_zh", "DAZHONG");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "GAZ");
        map.put("name", "gaz");
        map.put("name_zh", "gaz_zh");
        map.put("icon", "icon_gaz");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.gaz));
        map.put("sname_zh", "GEZI");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "PORSCHE");
        map.put("name", "porsche");
        map.put("name_zh", "porsche_zh");
        map.put("icon", "icon_porsche");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.porsche));
        map.put("sname_zh", "BAOSHIJIE");
        euroList.add(map);
        map = new HashMap();
        map.put("softPackageId", "LANDROVER_DEMO");
        map.put("name", "land_rover_demo");
        map.put("name_zh", "land_rover_demo_zh");
        map.put("icon", "icon_landrover");
        map.put("areaId", Integer.valueOf(1));
        map.put("sname", Integer.valueOf(C0136R.string.land_rover_demo));
        map.put("sname_zh", "LANDROVER_DEMO");
        euroList.add(map);
        return euroList;
    }

    public static List<HashMap<String, Object>> america() {
        List<HashMap<String, Object>> americaLists = new ArrayList();
        HashMap hashMap = new HashMap();
        HashMap<String, Object> map = new HashMap();
        map.put("softPackageId", "EOBD2");
        map.put("name", "eobd2");
        map.put("name_zh", "eobd2_cn");
        map.put("icon", "icon_eobd2");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        americaLists.add(map);
        map = new HashMap();
        map.put("softPackageId", "DEMO");
        map.put("name", "demo");
        map.put("name_zh", "demo_zh");
        map.put("icon", "icon_demo");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.f830a));
        map.put("sname_zh", "A");
        americaLists.add(map);
        map = new HashMap();
        map.put("softPackageId", "BXGM");
        map.put("name", "brazil_gm");
        map.put("name_zh", "brazil_gm_zh");
        map.put("icon", "icon_bxgm");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.brazil_gm));
        map.put("sname_zh", "BAXITONGYONG");
        americaLists.add(map);
        map = new HashMap();
        map.put("softPackageId", "FORD");
        map.put("name", "azford");
        map.put("name_zh", "azford_zh");
        map.put("icon", "icon_azford");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.azford));
        map.put("sname_zh", "AOZHOUFUTE");
        americaLists.add(map);
        map = new HashMap();
        map.put("softPackageId", "CHRYSLER");
        map.put("name", "chrysler");
        map.put("name_zh", "chrysler_zh");
        map.put("icon", "icon_chrysler");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.chrysler));
        map.put("sname_zh", "KELAISILE");
        americaLists.add(map);
        map = new HashMap();
        map.put("softPackageId", "GM");
        map.put("name", "gm");
        map.put("name_zh", "gm_zh");
        map.put("icon", "icon_gm");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.gm));
        map.put("sname_zh", "TONGYONG");
        americaLists.add(map);
        map = new HashMap();
        map.put("softPackageId", "USAFORD");
        map.put("name", "usa_ford");
        map.put("name_zh", "usa_ford_zh");
        map.put("icon", "icon_usaford");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.usa_ford));
        map.put("sname_zh", "MEIGUOFUTE");
        americaLists.add(map);
        map = new HashMap();
        map.put("softPackageId", "HOLDEN");
        map.put("name", "holden");
        map.put("name_zh", "holden_zh");
        map.put("icon", "icon_holden");
        map.put("areaId", Integer.valueOf(3));
        map.put("sname", Integer.valueOf(C0136R.string.holden));
        map.put("sname_zh", "HUODUN");
        americaLists.add(map);
        return americaLists;
    }
}
