package com.ifoer.util;

import com.cnlaunch.x431frame.C0136R;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class GetCarInfo {
    public static List<HashMap<String, Object>> amerLists;
    public static List<HashMap<String, Object>> asiaLists;
    public static List<HashMap<String, Object>> china;
    public static List<HashMap<String, Object>> euroLists;

    static {
        china = new ArrayList();
        asiaLists = new ArrayList();
        euroLists = new ArrayList();
        amerLists = new ArrayList();
    }

    public static void addData() {
        if (china.size() <= 0) {
            china = getChinaImages();
        }
        if (asiaLists.size() <= 0) {
            asiaLists = asia();
        }
        if (euroLists.size() <= 0) {
            euroLists = euro();
        }
        if (amerLists.size() <= 0) {
            amerLists = amer();
        }
    }

    public static List<HashMap<String, Object>> getChinaImages() {
        HashMap<String, Object> map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_alto));
        map.put("name_zh", Integer.valueOf(C0136R.string.alto_cn));
        map.put("name", Integer.valueOf(C0136R.string.alto));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_aokesi));
        map.put("name_zh", Integer.valueOf(C0136R.string.aokesi_cn));
        map.put("name", Integer.valueOf(C0136R.string.aokesi));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_baolong));
        map.put("name_zh", Integer.valueOf(C0136R.string.baolong_cn));
        map.put("name", Integer.valueOf(C0136R.string.baolong));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_beilv));
        map.put("name", Integer.valueOf(C0136R.string.beilv));
        map.put("name_zh", Integer.valueOf(C0136R.string.beilv_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_bjjeep));
        map.put("name", Integer.valueOf(C0136R.string.bjjeep));
        map.put("name_zh", Integer.valueOf(C0136R.string.bjjeep_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_bjxd));
        map.put("name", Integer.valueOf(C0136R.string.bjxd));
        map.put("name_zh", Integer.valueOf(C0136R.string.bjxd_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_bqzz));
        map.put("name", Integer.valueOf(C0136R.string.Bqzz));
        map.put("name_zh", Integer.valueOf(C0136R.string.Bqzz_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_chsuzuki));
        map.put("name", Integer.valueOf(C0136R.string.ca_suzuki));
        map.put("name_zh", Integer.valueOf(C0136R.string.ca_suzuki_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_chsuzuki));
        map.put("name", Integer.valueOf(C0136R.string.chsuzuki));
        map.put("name_zh", Integer.valueOf(C0136R.string.chsuzuki_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_changan));
        map.put("name", Integer.valueOf(C0136R.string.changan));
        map.put("name_zh", Integer.valueOf(C0136R.string.changan_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_changcheng));
        map.put("name", Integer.valueOf(C0136R.string.changcheng));
        map.put("name_zh", Integer.valueOf(C0136R.string.changcheng_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_changfeng));
        map.put("name", Integer.valueOf(C0136R.string.changfeng));
        map.put("name_zh", Integer.valueOf(C0136R.string.changfeng_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_changhe));
        map.put("name", Integer.valueOf(C0136R.string.changhe));
        map.put("name_zh", Integer.valueOf(C0136R.string.changhe_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_changanford));
        map.put("name", Integer.valueOf(C0136R.string.chinaford));
        map.put("name_zh", Integer.valueOf(C0136R.string.chinaford_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_tjtoyota));
        map.put("name", Integer.valueOf(C0136R.string.china_toyota));
        map.put("name_zh", Integer.valueOf(C0136R.string.china_toyota_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_cqisuzu));
        map.put("name", Integer.valueOf(C0136R.string.cqisuzu));
        map.put("name_zh", Integer.valueOf(C0136R.string.cqisuzu_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_cadi));
        map.put("name", Integer.valueOf(C0136R.string.dadi));
        map.put("name_zh", Integer.valueOf(C0136R.string.dadi_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_fukang));
        map.put("name", Integer.valueOf(C0136R.string.df_citroen));
        map.put("name_zh", Integer.valueOf(C0136R.string.df_citroen_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_dfhonda));
        map.put("name", Integer.valueOf(C0136R.string.dfhonda));
        map.put("name_zh", Integer.valueOf(C0136R.string.dfhonda_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_dfnissan));
        map.put("name", Integer.valueOf(C0136R.string.dfnissan));
        map.put("name_zh", Integer.valueOf(C0136R.string.dfnissan_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_dfpeugeot));
        map.put("name", Integer.valueOf(C0136R.string.dfpeugeot));
        map.put("name_zh", Integer.valueOf(C0136R.string.dfpeugeot_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_yueda));
        map.put("name", Integer.valueOf(C0136R.string.df_yueda));
        map.put("name_zh", Integer.valueOf(C0136R.string.df_yueda_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_dfcng_ty));
        map.put("name", Integer.valueOf(C0136R.string.dfcng_ty));
        map.put("name_zh", Integer.valueOf(C0136R.string.dfcng_ty_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_dfxk));
        map.put("name", Integer.valueOf(C0136R.string.dfxk));
        map.put("name_zh", Integer.valueOf(C0136R.string.dfxk_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_dongnan));
        map.put("name", Integer.valueOf(C0136R.string.dongnan));
        map.put("name_zh", Integer.valueOf(C0136R.string.dongnan_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_eobd2));
        map.put("name", Integer.valueOf(C0136R.string.eobd2));
        map.put("name_zh", Integer.valueOf(C0136R.string.eobd2_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_hmazda_zy));
        map.put("name", Integer.valueOf(C0136R.string.faw_mazda));
        map.put("name_zh", Integer.valueOf(C0136R.string.faw_mazda_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_shvw));
        map.put("name", Integer.valueOf(C0136R.string.faw_vw));
        map.put("name_zh", Integer.valueOf(C0136R.string.faw_vw_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_yqef));
        map.put("name", Integer.valueOf(C0136R.string.faw_ef));
        map.put("name_zh", Integer.valueOf(C0136R.string.faw_ef_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_yqhtty));
        map.put("name", Integer.valueOf(C0136R.string.faw_ht));
        map.put("name_zh", Integer.valueOf(C0136R.string.faw_ht_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_fudizy));
        map.put("name", Integer.valueOf(C0136R.string.fudizy));
        map.put("name_zh", Integer.valueOf(C0136R.string.fudizy_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_fuqi));
        map.put("name", Integer.valueOf(C0136R.string.fuqi));
        map.put("name_zh", Integer.valueOf(C0136R.string.fuqi_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_futian));
        map.put("name", Integer.valueOf(C0136R.string.futian));
        map.put("name_zh", Integer.valueOf(C0136R.string.futian_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_fzqiche));
        map.put("name", Integer.valueOf(C0136R.string.fuzhou));
        map.put("name_zh", Integer.valueOf(C0136R.string.fuzhou_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_fzmazda));
        map.put("name", Integer.valueOf(C0136R.string.fz_mazid));
        map.put("name_zh", Integer.valueOf(C0136R.string.fz_mazid_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_yangcheng));
        map.put("name", Integer.valueOf(C0136R.string.gaig));
        map.put("name_zh", Integer.valueOf(C0136R.string.gaig_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_haoqing));
        map.put("name", Integer.valueOf(C0136R.string.geely));
        map.put("name_zh", Integer.valueOf(C0136R.string.geely_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_jiao));
        map.put("name", Integer.valueOf(C0136R.string.gonow));
        map.put("name_zh", Integer.valueOf(C0136R.string.gonow_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_gzhonda));
        map.put("name", Integer.valueOf(C0136R.string.gz_honda));
        map.put("name_zh", Integer.valueOf(C0136R.string.gz_honda_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_hafei));
        map.put("name", Integer.valueOf(C0136R.string.hafei));
        map.put("name_zh", Integer.valueOf(C0136R.string.hafei_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_hbqc));
        map.put("name", Integer.valueOf(C0136R.string.hbqc));
        map.put("name_zh", Integer.valueOf(C0136R.string.hbqc_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_hcbmw));
        map.put("name", Integer.valueOf(C0136R.string.hc_bmw));
        map.put("name_zh", Integer.valueOf(C0136R.string.hc_bmw_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_heibao));
        map.put("name", Integer.valueOf(C0136R.string.heibao));
        map.put("name_zh", Integer.valueOf(C0136R.string.heibao_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_htjt));
        map.put("name", Integer.valueOf(C0136R.string.htjt));
        map.put("name_zh", Integer.valueOf(C0136R.string.htjt_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_huapu));
        map.put("name", Integer.valueOf(C0136R.string.huapu));
        map.put("name_zh", Integer.valueOf(C0136R.string.huapu_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_huayang));
        map.put("name", Integer.valueOf(C0136R.string.huayang));
        map.put("name_zh", Integer.valueOf(C0136R.string.huayang_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_jinanyunbao));
        map.put("name", Integer.valueOf(C0136R.string.jinganyunbao));
        map.put("name_zh", Integer.valueOf(C0136R.string.jinganyunbao_cn));
        china.add(map);
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_jincheng));
        map.put("name", Integer.valueOf(C0136R.string.jincheng));
        map.put("name_zh", Integer.valueOf(C0136R.string.jincheng_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_isuzu));
        map.put("name", Integer.valueOf(C0136R.string.jmc));
        map.put("name_zh", Integer.valueOf(C0136R.string.jmc_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_jinlong));
        map.put("name", Integer.valueOf(C0136R.string.king_long));
        map.put("name_zh", Integer.valueOf(C0136R.string.king_long_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_lifan));
        map.put("name", Integer.valueOf(C0136R.string.lifan));
        map.put("name_zh", Integer.valueOf(C0136R.string.lifan_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_liuwei_ty));
        map.put("name", Integer.valueOf(C0136R.string.liuwei));
        map.put("name_zh", Integer.valueOf(C0136R.string.liuwei_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_lufeng));
        map.put("name", Integer.valueOf(C0136R.string.lufeng));
        map.put("name_zh", Integer.valueOf(C0136R.string.lufeng_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_meiya));
        map.put("name", Integer.valueOf(C0136R.string.meiya));
        map.put("name_zh", Integer.valueOf(C0136R.string.meiya_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_ijfiat));
        map.put("name", Integer.valueOf(C0136R.string.nanjing_fiat));
        map.put("name_zh", Integer.valueOf(C0136R.string.nanjing_fiat_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_jac));
        map.put("name", Integer.valueOf(C0136R.string.refine));
        map.put("name_zh", Integer.valueOf(C0136R.string.refine_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_saicroewe));
        map.put("name", Integer.valueOf(C0136R.string.roewe));
        map.put("name_zh", Integer.valueOf(C0136R.string.roewe_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_saibao));
        map.put("name", Integer.valueOf(C0136R.string.saibao));
        map.put("name_zh", Integer.valueOf(C0136R.string.saibao_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_saicmg));
        map.put("name", Integer.valueOf(C0136R.string.saic_mg));
        map.put("name_zh", Integer.valueOf(C0136R.string.saic_mg_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_sgm));
        map.put("name", Integer.valueOf(C0136R.string.sh_gm));
        map.put("name_zh", Integer.valueOf(C0136R.string.sh_gm_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_shvw));
        map.put("name", Integer.valueOf(C0136R.string.sh_vw));
        map.put("name_zh", Integer.valueOf(C0136R.string.sh_vw_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_shuanghuan));
        map.put("name", Integer.valueOf(C0136R.string.shuanghuan));
        map.put("name_zh", Integer.valueOf(C0136R.string.shuanghuan_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_tianma));
        map.put("name", Integer.valueOf(C0136R.string.tianma));
        map.put("name_zh", Integer.valueOf(C0136R.string.tianma_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_tianye));
        map.put("name", Integer.valueOf(C0136R.string.tianye));
        map.put("name_zh", Integer.valueOf(C0136R.string.tianye_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_tongbao));
        map.put("name", Integer.valueOf(C0136R.string.tongbao));
        map.put("name_zh", Integer.valueOf(C0136R.string.tongbao_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_wanfeng));
        map.put("name", Integer.valueOf(C0136R.string.wanfeng));
        map.put("name_zh", Integer.valueOf(C0136R.string.wanfeng_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_wantong));
        map.put("name", Integer.valueOf(C0136R.string.wantong));
        map.put("name_zh", Integer.valueOf(C0136R.string.wantong_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_xghc));
        map.put("name", Integer.valueOf(C0136R.string.xghc));
        map.put("name_zh", Integer.valueOf(C0136R.string.xghc_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_xiali));
        map.put("name", Integer.valueOf(C0136R.string.xiali));
        map.put("name_zh", Integer.valueOf(C0136R.string.xiali_cn));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_xindadi));
        map.put("name", Integer.valueOf(C0136R.string.xindadi));
        map.put("name_zh", Integer.valueOf(C0136R.string.xindadi_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_xinkai));
        map.put("name", Integer.valueOf(C0136R.string.xinkai));
        map.put("name_zh", Integer.valueOf(C0136R.string.xinkai_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_xintiandi));
        map.put("name", Integer.valueOf(C0136R.string.xintiandi));
        map.put("name_zh", Integer.valueOf(C0136R.string.xintiandi_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_yangzi));
        map.put("name", Integer.valueOf(C0136R.string.yangzi));
        map.put("name_zh", Integer.valueOf(C0136R.string.yangzi_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_yizhong));
        map.put("name", Integer.valueOf(C0136R.string.yizhong));
        map.put("name_zh", Integer.valueOf(C0136R.string.yizhong_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_yuejin));
        map.put("name", Integer.valueOf(C0136R.string.yuejin));
        map.put("name_zh", Integer.valueOf(C0136R.string.yuejin_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_zhongshun));
        map.put("name", Integer.valueOf(C0136R.string.polarsun));
        map.put("name_zh", Integer.valueOf(C0136R.string.polarsun_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_zhongxing));
        map.put("name", Integer.valueOf(C0136R.string.zhongxing));
        map.put("name_zh", Integer.valueOf(C0136R.string.zhongxing_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_zhongtai));
        map.put("name", Integer.valueOf(C0136R.string.zotye));
        map.put("name_zh", Integer.valueOf(C0136R.string.zotye_zh));
        china.add(map);
        map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_zznissan));
        map.put("name", Integer.valueOf(C0136R.string.zz_nissan));
        map.put("name_zh", Integer.valueOf(C0136R.string.zz_nissan_zh));
        china.add(map);
        return china;
    }

    public static List<HashMap<String, Object>> euro() {
        HashMap<String, Object> map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_audi));
        map.put("name", Integer.valueOf(C0136R.string.audi));
        map.put("name_zh", Integer.valueOf(C0136R.string.audi_zh));
        euroLists.add(map);
        HashMap<String, Object> map1 = new HashMap();
        map1.put("icon", Integer.valueOf(C0136R.drawable.icon_benz));
        map1.put("name", Integer.valueOf(C0136R.string.benz));
        map1.put("name_zh", Integer.valueOf(C0136R.string.benz_zh));
        euroLists.add(map1);
        HashMap<String, Object> map2 = new HashMap();
        map2.put("icon", Integer.valueOf(C0136R.drawable.icon_bmw));
        map2.put("name", Integer.valueOf(C0136R.string.bmw));
        map2.put("name_zh", Integer.valueOf(C0136R.string.bmw_zh));
        euroLists.add(map2);
        HashMap<String, Object> map3 = new HashMap();
        map3.put("icon", Integer.valueOf(C0136R.drawable.icon_citroen));
        map3.put("name", Integer.valueOf(C0136R.string.citroen));
        map3.put("name_zh", Integer.valueOf(C0136R.string.citroen_zh));
        euroLists.add(map3);
        HashMap<String, Object> map4 = new HashMap();
        map4.put("icon", Integer.valueOf(C0136R.drawable.icon_dacia));
        map4.put("name", Integer.valueOf(C0136R.string.dacia));
        map4.put("name_zh", Integer.valueOf(C0136R.string.dacia_zh));
        euroLists.add(map4);
        HashMap<String, Object> map5 = new HashMap();
        map5.put("icon", Integer.valueOf(C0136R.drawable.icon_euroford));
        map5.put("name", Integer.valueOf(C0136R.string.ford));
        map5.put("name_zh", Integer.valueOf(C0136R.string.ford_zh));
        euroLists.add(map5);
        HashMap<String, Object> map6 = new HashMap();
        map6.put("icon", Integer.valueOf(C0136R.drawable.icon_fiat));
        map6.put("name", Integer.valueOf(C0136R.string.fiat));
        map6.put("name_zh", Integer.valueOf(C0136R.string.fiat_zh));
        euroLists.add(map6);
        HashMap<String, Object> map7 = new HashMap();
        map7.put("icon", Integer.valueOf(C0136R.drawable.icon_gmsa));
        map7.put("name", Integer.valueOf(C0136R.string.gmsa));
        map7.put("name_zh", Integer.valueOf(C0136R.string.gmsa_zh));
        euroLists.add(map7);
        HashMap<String, Object> map9 = new HashMap();
        map9.put("icon", Integer.valueOf(C0136R.drawable.icon_jaguar));
        map9.put("name", Integer.valueOf(C0136R.string.jaguar));
        map9.put("name_zh", Integer.valueOf(C0136R.string.jaguar_zh));
        euroLists.add(map9);
        HashMap<String, Object> map10 = new HashMap();
        map10.put("icon", Integer.valueOf(C0136R.drawable.icon_lancia));
        map10.put("name", Integer.valueOf(C0136R.string.lancia));
        map10.put("name_zh", Integer.valueOf(C0136R.string.lancia_zh));
        euroLists.add(map10);
        HashMap<String, Object> map11 = new HashMap();
        map11.put("icon", Integer.valueOf(C0136R.drawable.icon_landrover));
        map11.put("name", Integer.valueOf(C0136R.string.land_rover));
        map11.put("name_zh", Integer.valueOf(C0136R.string.land_rover_zh));
        euroLists.add(map11);
        HashMap<String, Object> map12 = new HashMap();
        map12.put("icon", Integer.valueOf(C0136R.drawable.icon_opel));
        map12.put("name", Integer.valueOf(C0136R.string.opel));
        map12.put("name_zh", Integer.valueOf(C0136R.string.opel_zh));
        euroLists.add(map12);
        HashMap<String, Object> map13 = new HashMap();
        map13.put("icon", Integer.valueOf(C0136R.drawable.icon_peugeot));
        map13.put("name", Integer.valueOf(C0136R.string.peugeot));
        map13.put("name_zh", Integer.valueOf(C0136R.string.peugeot_zh));
        euroLists.add(map13);
        HashMap<String, Object> map14 = new HashMap();
        map14.put("icon", Integer.valueOf(C0136R.drawable.icon_porsche));
        map14.put("name", Integer.valueOf(C0136R.string.porsche));
        map14.put("name_zh", Integer.valueOf(C0136R.string.porsche_zh));
        euroLists.add(map14);
        HashMap<String, Object> map16 = new HashMap();
        map16.put("icon", Integer.valueOf(C0136R.drawable.icon_renault));
        map16.put("name", Integer.valueOf(C0136R.string.renault));
        map16.put("name_zh", Integer.valueOf(C0136R.string.renault_zh));
        euroLists.add(map16);
        HashMap<String, Object> map17 = new HashMap();
        map17.put("icon", Integer.valueOf(C0136R.drawable.icon_romeo));
        map17.put("name", Integer.valueOf(C0136R.string.romeo));
        map17.put("name_zh", Integer.valueOf(C0136R.string.romeo_zh));
        euroLists.add(map17);
        HashMap<String, Object> map18 = new HashMap();
        map18.put("icon", Integer.valueOf(C0136R.drawable.icon_rover));
        map18.put("name", Integer.valueOf(C0136R.string.rover));
        map18.put("name_zh", Integer.valueOf(C0136R.string.rover_zh));
        euroLists.add(map18);
        HashMap<String, Object> map19 = new HashMap();
        map19.put("icon", Integer.valueOf(C0136R.drawable.icon_saab));
        map19.put("name", Integer.valueOf(C0136R.string.saab));
        map19.put("name_zh", Integer.valueOf(C0136R.string.saab_zh));
        euroLists.add(map19);
        HashMap<String, Object> map20 = new HashMap();
        map20.put("icon", Integer.valueOf(C0136R.drawable.icon_seat));
        map20.put("name", Integer.valueOf(C0136R.string.seat));
        map20.put("name_zh", Integer.valueOf(C0136R.string.seat_zh));
        euroLists.add(map20);
        HashMap<String, Object> map21 = new HashMap();
        map21.put("icon", Integer.valueOf(C0136R.drawable.icon_skoda));
        map21.put("name", Integer.valueOf(C0136R.string.skoda));
        map21.put("name_zh", Integer.valueOf(C0136R.string.skoda_zh));
        euroLists.add(map21);
        HashMap<String, Object> map22 = new HashMap();
        map22.put("icon", Integer.valueOf(C0136R.drawable.icon_smart));
        map22.put("name", Integer.valueOf(C0136R.string.smart));
        map22.put("name_zh", Integer.valueOf(C0136R.string.smart_zh));
        euroLists.add(map22);
        HashMap<String, Object> map23 = new HashMap();
        map23.put("icon", Integer.valueOf(C0136R.drawable.icon_sprinter));
        map23.put("name", Integer.valueOf(C0136R.string.sprinter));
        map23.put("name_zh", Integer.valueOf(C0136R.string.sprinter_zh));
        euroLists.add(map23);
        HashMap<String, Object> map24 = new HashMap();
        map24.put("icon", Integer.valueOf(C0136R.drawable.icon_vaz));
        map24.put("name", Integer.valueOf(C0136R.string.vaz));
        map24.put("name_zh", Integer.valueOf(C0136R.string.vaz_zh));
        euroLists.add(map24);
        HashMap<String, Object> map25 = new HashMap();
        map25.put("icon", Integer.valueOf(C0136R.drawable.icon_volvo));
        map25.put("name", Integer.valueOf(C0136R.string.volvo));
        map25.put("name_zh", Integer.valueOf(C0136R.string.volvo_zh));
        euroLists.add(map25);
        HashMap<String, Object> map26 = new HashMap();
        map26.put("icon", Integer.valueOf(C0136R.drawable.icon_vw));
        map26.put("name", Integer.valueOf(C0136R.string.vw));
        map26.put("name_zh", Integer.valueOf(C0136R.string.vw_zh));
        euroLists.add(map26);
        return euroLists;
    }

    public static List<HashMap<String, Object>> amer() {
        HashMap<String, Object> map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_vw));
        map.put("name", Integer.valueOf(C0136R.string.vw));
        map.put("name_zh", Integer.valueOf(C0136R.string.vw_zh));
        amerLists.add(map);
        HashMap<String, Object> map1 = new HashMap();
        map1.put("icon", Integer.valueOf(C0136R.drawable.icon_bxgm));
        map1.put("name", Integer.valueOf(C0136R.string.brazil_gm));
        map1.put("name_zh", Integer.valueOf(C0136R.string.brazil_gm_zh));
        amerLists.add(map1);
        HashMap<String, Object> map2 = new HashMap();
        map2.put("icon", Integer.valueOf(C0136R.drawable.icon_chrysler));
        map2.put("name", Integer.valueOf(C0136R.string.chrysler));
        map2.put("name_zh", Integer.valueOf(C0136R.string.chrysler_zh));
        amerLists.add(map2);
        HashMap<String, Object> map3 = new HashMap();
        map3.put("icon", Integer.valueOf(C0136R.drawable.icon_gm));
        map3.put("name", Integer.valueOf(C0136R.string.gm));
        map3.put("name_zh", Integer.valueOf(C0136R.string.gm_zh));
        amerLists.add(map3);
        HashMap<String, Object> map4 = new HashMap();
        map4.put("icon", Integer.valueOf(C0136R.drawable.icon_usaford));
        map4.put("name", Integer.valueOf(C0136R.string.usa_ford));
        map4.put("name_zh", Integer.valueOf(C0136R.string.usa_ford_zh));
        amerLists.add(map4);
        return amerLists;
    }

    public static List<HashMap<String, Object>> asia() {
        HashMap<String, Object> map = new HashMap();
        map.put("icon", Integer.valueOf(C0136R.drawable.icon_acura));
        map.put("name", Integer.valueOf(C0136R.string.acura));
        map.put("name_zh", Integer.valueOf(C0136R.string.acura_zh));
        asiaLists.add(map);
        HashMap<String, Object> map1 = new HashMap();
        map1.put("icon", Integer.valueOf(C0136R.drawable.icon_daewoo));
        map1.put("name", Integer.valueOf(C0136R.string.daewoo));
        map1.put("name_zh", Integer.valueOf(C0136R.string.daewoo_zh));
        asiaLists.add(map1);
        HashMap<String, Object> map2 = new HashMap();
        map2.put("icon", Integer.valueOf(C0136R.drawable.icon_daihatsu));
        map2.put("name", Integer.valueOf(C0136R.string.daihatsu));
        map2.put("name_zh", Integer.valueOf(C0136R.string.daihatsu_zh));
        asiaLists.add(map2);
        HashMap<String, Object> map3 = new HashMap();
        map3.put("icon", Integer.valueOf(C0136R.drawable.icon_holden));
        map3.put("name", Integer.valueOf(C0136R.string.holden));
        map3.put("name_zh", Integer.valueOf(C0136R.string.holden_zh));
        asiaLists.add(map3);
        HashMap<String, Object> map4 = new HashMap();
        map4.put("icon", Integer.valueOf(C0136R.drawable.icon_honda));
        map4.put("name", Integer.valueOf(C0136R.string.honda));
        map4.put("name_zh", Integer.valueOf(C0136R.string.honda_zh));
        asiaLists.add(map4);
        HashMap<String, Object> map5 = new HashMap();
        map5.put("icon", Integer.valueOf(C0136R.drawable.icon_hyundai));
        map5.put("name", Integer.valueOf(C0136R.string.hyundai));
        map5.put("name_zh", Integer.valueOf(C0136R.string.hyundai_zh));
        asiaLists.add(map5);
        HashMap<String, Object> map6 = new HashMap();
        map6.put("icon", Integer.valueOf(C0136R.drawable.icon_indonesiasuzuki));
        map6.put("name", Integer.valueOf(C0136R.string.indonesia_suzuki));
        map6.put("name_zh", Integer.valueOf(C0136R.string.indonesia_suzuki_zh));
        asiaLists.add(map6);
        HashMap<String, Object> map7 = new HashMap();
        map7.put("icon", Integer.valueOf(C0136R.drawable.icon_infiniti));
        map7.put("name", Integer.valueOf(C0136R.string.infiniti));
        map7.put("name_zh", Integer.valueOf(C0136R.string.infiniti_zh));
        asiaLists.add(map7);
        HashMap<String, Object> map8 = new HashMap();
        map8.put("icon", Integer.valueOf(C0136R.drawable.icon_kia));
        map8.put("name", Integer.valueOf(C0136R.string.kia));
        map8.put("name_zh", Integer.valueOf(C0136R.string.kia_zh));
        asiaLists.add(map8);
        HashMap<String, Object> map9 = new HashMap();
        map9.put("icon", Integer.valueOf(C0136R.drawable.icon_mahindra));
        map9.put("name", Integer.valueOf(C0136R.string.mahindra));
        map9.put("name_zh", Integer.valueOf(C0136R.string.mahindra_zh));
        asiaLists.add(map9);
        HashMap<String, Object> map10 = new HashMap();
        map10.put("icon", Integer.valueOf(C0136R.drawable.icon_maruti));
        map10.put("name", Integer.valueOf(C0136R.string.maruti));
        map10.put("name_zh", Integer.valueOf(C0136R.string.maruti_zh));
        asiaLists.add(map10);
        HashMap<String, Object> map11 = new HashMap();
        map11.put("icon", Integer.valueOf(C0136R.drawable.icon_mazda));
        map11.put("name", Integer.valueOf(C0136R.string.mazda));
        map11.put("name_zh", Integer.valueOf(C0136R.string.mazda_zh));
        asiaLists.add(map11);
        HashMap<String, Object> map12 = new HashMap();
        map12.put("icon", Integer.valueOf(C0136R.drawable.icon_mitsubishi));
        map12.put("name", Integer.valueOf(C0136R.string.mitsubishi));
        map12.put("name_zh", Integer.valueOf(C0136R.string.mitsubishi_zh));
        asiaLists.add(map12);
        HashMap<String, Object> map13 = new HashMap();
        map13.put("icon", Integer.valueOf(C0136R.drawable.icon_nissan));
        map13.put("name", Integer.valueOf(C0136R.string.nissan));
        map13.put("name_zh", Integer.valueOf(C0136R.string.nissan_zh));
        asiaLists.add(map13);
        HashMap<String, Object> map14 = new HashMap();
        map14.put("icon", Integer.valueOf(C0136R.drawable.icon_perodua));
        map14.put("name", Integer.valueOf(C0136R.string.perodua));
        map14.put("name_zh", Integer.valueOf(C0136R.string.perodua_zh));
        asiaLists.add(map14);
        HashMap<String, Object> map15 = new HashMap();
        map15.put("icon", Integer.valueOf(C0136R.drawable.icon_proton));
        map15.put("name", Integer.valueOf(C0136R.string.proton));
        map15.put("name_zh", Integer.valueOf(C0136R.string.proton_zh));
        asiaLists.add(map15);
        HashMap<String, Object> map16 = new HashMap();
        map16.put("icon", Integer.valueOf(C0136R.drawable.icon_ssangyong));
        map16.put("name", Integer.valueOf(C0136R.string.ssangyong));
        map16.put("name_zh", Integer.valueOf(C0136R.string.ssangyong_zh));
        asiaLists.add(map16);
        HashMap<String, Object> map17 = new HashMap();
        map17.put("icon", Integer.valueOf(C0136R.drawable.icon_subaru));
        map17.put("name", Integer.valueOf(C0136R.string.subaru));
        map17.put("name_zh", Integer.valueOf(C0136R.string.subaru_zh));
        asiaLists.add(map17);
        HashMap<String, Object> map18 = new HashMap();
        map18.put("icon", Integer.valueOf(C0136R.drawable.icon_suzuki));
        map18.put("name", Integer.valueOf(C0136R.string.suzuki));
        map18.put("name_zh", Integer.valueOf(C0136R.string.suzuki_zh));
        asiaLists.add(map18);
        HashMap<String, Object> map19 = new HashMap();
        map19.put("icon", Integer.valueOf(C0136R.drawable.icon_tata));
        map19.put("name", Integer.valueOf(C0136R.string.tata));
        map19.put("name_zh", Integer.valueOf(C0136R.string.tata_zh));
        asiaLists.add(map19);
        HashMap<String, Object> map20 = new HashMap();
        map20.put("icon", Integer.valueOf(C0136R.drawable.icon_toyota));
        map20.put("name", Integer.valueOf(C0136R.string.toyota));
        map20.put("name_zh", Integer.valueOf(C0136R.string.toyota_zh));
        asiaLists.add(map20);
        return asiaLists;
    }
}
